### ISSUE TITLE
TalibanPearls/Pearls in general

### ISSUE THREAD

**Issue by Sheeqzy** [Imanity-Software/ImanitySpigot3-git#101]
### Expected behavior

So that you can look at the fence gate or shift and that you can pearl thru it.
And that you can pearl in to 1x1

### Observed/Actual behavior

It won't pearl thru it unless you are outside of certain range.
You can' pearl in to 1x1

### Steps/models to reproduce

https://imgur.com/a/fiDftkh
https://imgur.com/a/UWyJVZ6

### Plugin list

https://i.imgur.com/qf0VNHG.png

### ImanitySpigot3 version

2021.11.1 LTS BUILD 6

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

**Comment by Whizyyy** [comment]
Hello, this is working on my side. Please, can you send your pearl config so I can see if there is something wrong with what you expect from it

**Comment by Whizyyy** [comment]
Closed due to inactivity. I cannot reproduce so considering it was just a wrong setup.
