### ISSUE TITLE
Request for Practice Addon support

### ISSUE THREAD

**Issue by GA1-Project** [Imanity-Software/ImanitySpigot3-git#102]
### Is your feature request related to a problem?

Because I am planning to use Yang practice in ispigot.

### Describe the solution you'd like.

I would like to see Yang Practice support added to the Practice Addon.
https://github.com/Panda-Community/YangAPI
https://www.mc-market.org/resources/21338/

### Describe alternatives you've considered.

I don't know what the description means, so I'll leave it blank.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest ImanitySpigot3.

**Comment by Whizyyy** [comment]
Support added, thanks for the feature request.
