### ISSUE TITLE
FastAsyncWorldEdit

### ISSUE THREAD

**Issue by ignMixha** [Imanity-Software/ImanitySpigot3-git#104]
### Expected behavior

I am expected to see my server start up like normal.

### Observed/Actual behavior

The server will start up and then as soon as it loads 'FastAsyncWorldEdit' it will just proceed to shutdown.

### Steps/models to reproduce

Just place the latest 1.8 version of 'FastAsyncWorldEdit' which is 'FastAsyncWorldEdit-bukkit-21.03.09-a5e5590-1285-22.3.8' i think.

### Plugin list

(1) FastAsyncWorldEdit

### ImanitySpigot3 version

spigotJarVersion: 2022.03.1 BUILD 2

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

**Comment by HappyAreaBean** [comment]
Hello, what version of Java are you using? 
FAWE (Legacy) is not supported by Java 17. If you are using Java 17, then please downgrade to Java 11 and try again.
If the problem persists after you downgrade to Java 11. Please send your server logs so we can get more details.

**Comment by ignMixha** [comment]
Java Version: 8 & 11 both tried

Error: https://pastebin.com/nK1eD77G

**Comment by HappyAreaBean** [comment]
I tried the exact same version of FAWE in the error you sent (https://ci.athion.net/job/FastAsyncWorldEdit-Legacy/1285/) in both Java 8 and 11 and it worked fine. Are you sure you're not using Java 17?

**Comment by ignMixha** [comment]
I have sorted out this issue. I uninstalled all java versions (8 & 11) deleted files, restarted pc and just installed java 8 with jdk.

**Comment by ArifErdoganK** [comment]
For Minecraft version 1.21, entry support has been made mandatory with Java 17 by ViaVersion. FAWE is no longer used on 1.8.8 ImanitySpigot. What do we need to do about this?
