### ISSUE TITLE
BAC client crash when making left or right click on the server in the air or on the ground

### ISSUE THREAD

**Issue by Synix99** [Imanity-Software/ImanitySpigot3-git#107]
### Stack trace

```
[paste your stack trace or a https://paste.imanity.dev/ link here!](https://paste.imanity.dev/p5d6kbs)
```

### Plugin list

ParticleNativeAPI (3.1.0), WorldEdit (6.1.5;4651611), Citizens (2.0.16-SNAPSHOT (build 1267)), WorldLoader (1.1), ViaVersion (4.1.1), ProtocolLib (4.7.0), WorldGuard (6.1), ViaRewind (2.0.2), NetworkManager (2.10.10), AdvancedReplay (1.8.1), AntiTAB (1.0.1), WGRegionEvents (1.1)

### Steps/models to reproduce (if known)

You start the BAC client with the version "1.7.10", then enter a server that uses ImanitySpigot3 and only after a left or right click (Walking around is not a problem / no matter on in the air or on a block) the client crashes, this happens only if ImanitySpigot3 is on the server.

With BAC "1.8.9" or Luna Client "1.8" or default Minecraft with "1.7.10" this error did NOT occur!

### ImanitySpigot3 version

spigotJarVersion: 2022.03.1 BUILD 2

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

**Comment by LeeGodSRC** [comment]
Can you reproduce the same bug with only the **latest** version of via-version and via-rewind? and no other plugins
