### ISSUE TITLE
Strange crash during a clean installation.

### ISSUE THREAD

**Issue by Kydaix** [Imanity-Software/ImanitySpigot3-git#108]
### Stack trace

```
https://paste.imanity.dev/Eb7xPOF
```
**iSpigot version:** 2022.05.1 LTS BUILD 2
**Java version:** 17

During a clean installation of iSpigot, i.e. as if I was creating a brand new server, a strange crash occurred. I had nothing except Rancha. I never had this problem with previous versions. I suppose this bug is related to the new AsyncFastLight addon.

### Plugin list

None.

### Steps/models to reproduce (if known)

1. Launch Rancha with the Aikar's startup flags.
2. Enter your license.
3. Select the 2022.05.1 LTS BUILD 2 version.
4. Wait and see.

### ImanitySpigot3 version

2022.05.1 LTS BUILD 2

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

**Comment by LeeGodSRC** [comment]
Fixed in latest version
