### ISSUE TITLE
Tnt bug

### ISSUE THREAD

**Issue by xpghard** [Imanity-Software/ImanitySpigot3-git#109]
### Expected behavior

I want to see tnt working video: https://youtu.be/Aq0ek79iVqo

### Observed/Actual behavior

.

### Steps/models to reproduce

.

### Plugin list

![image](https://user-images.githubusercontent.com/100840109/166646884-9912aab1-2dbf-4831-aeec-22ae04b0a0e1.png)

### ImanitySpigot3 version

2022.05.1 LTS BUILD 2

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

**Comment by LeeGodSRC** [comment]
Fixed in ImanitySpigot3 2022.5.3 BUILD 2
