### ISSUE TITLE
[Usability Issue] Enable RCON before rancha authentication

### ISSUE THREAD

**Issue by LeeGodSRC** [Imanity-Software/ImanitySpigot3-git#11]
### Is your feature request related to a problem?

RCON were used for some servers for remote console
But RCON was defaultly startup after Minecraft Server were started
So it would be annoying for people who hasn't authenticate

### Describe the solution you'd like.

Enable RCON before rancha authentication

### Describe alternatives you've considered.

You can use solutions other then RCON but would be good to natively supported

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest ImanitySpigot3.

**Comment by xpghard** [comment]
This feature no longer makes sense. You can add licenses using the flag -Dimanity.license={licence}, if there will be an option to still select versions using the flag, I don't see the point of introducing this.

**Comment by Kydaix** [comment]
Some hosts do not allow the modification of the launch parameters.

**Comment by xpghard** [comment]
@Kydaix If they don't allow it then automatically running imanity without problems on versions 8+ is impossible....
