### ISSUE TITLE
Async gui

### ISSUE THREAD

**Issue by xpg-hard** [Imanity-Software/ImanitySpigot3-git#111]
### Is your feature request related to a problem?

No

### Describe the solution you'd like.

When you open the gui it opens in async. It would be nice if this could be enabled in config

### Describe alternatives you've considered.

https://dev.bukkit.org/projects/asyncblockevents

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest ImanitySpigot3.

**Comment by LeeGodSRC** [comment]
Don't really think there is any good case to making gui async, it shouldn't be changed to keep vanilla feature and plugins to work as intended. also in real situation gui's load is like nothing
