### ISSUE TITLE
-Dimanity.licence java flag not working

### ISSUE THREAD

**Issue by osu** [Imanity-Software/ImanitySpigot3-git#112]
### Expected behavior

While putting ```-Dimanity.license={licence}``` it should've launched the spigot without asking for the licence (on Rancha)

### Observed/Actual behavior

https://i.imgur.com/H4P4mgs.png

### Steps/models to reproduce

Put ```-Dimanity.license={licence}``` in your flag on start.sh

### Plugin list

None.

### ImanitySpigot3 version

2022.05.1 LTS BUILD 2

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

**Comment by xpg-hard** [comment]
You posted a link to your license in imgur and anyone can steal it for private purposes. Mask the license and post the link to imgur again. If you are concerned that someone has used it, contact the ispigot administration.

**Comment by osu** [comment]
> You posted a link to your license in imgur and anyone can steal it for private purposes. Mask the license and post the link to imgur again. If you are concerned that someone has used it, contact the ispigot administration.

ROFL my bad I thought i uploaded the right license, wrong screenshot ! Thanks alot

**Comment by LeeGodSRC** [comment]
This feature hasn't been published yet.
but for some reason our staff thought it was already published so he accidentally leaked the feature.
