### ISSUE TITLE
Cpu is overloading

### ISSUE THREAD

**Issue by Daniels32** [Imanity-Software/ImanitySpigot3-git#114]
### Expected behavior

Hello, few days ago I bought imanityspigot, before I used nachospigot and on 20-30 players I had 30% cpu usage, with imanityspigot without players I have 20% cpu usage. Can you help please or can I get refund?

### Observed/Actual behavior

.

### Steps/models to reproduce

.

### Plugin list

.

### ImanitySpigot3 version

2022.05.1 LTS BUILD 2

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

### Other

.

**Comment by xpg-hard** [comment]
If you don't send us a report so that we can find out what's using so much CPU, what plugins you have, your machine and so on, we won't be able to help you. If you can send a report from spark(https://spark.lucko.me/) and give as much information as possible.

**Comment by Kydaix** [comment]
Hello ! I would like to give my opinion on your report!

Personally, I've been using iSpigot for a while, learning how to use it, looking at and discovering its options. On my side, with 8 plugins and a map (Lobby), and my modified server configurations, I'm running around 15% for CPU (Intel E5-1650v4), and RAM around 150MB (DDR4 ECC 2400MHz) with me connected. (Shared Hosting)

So I'm just giving my opinion, but I think it's really good considering the configuration the server is running on.

**Comment by LeeGodSRC** [comment]
take too long to response, closing for now
