### ISSUE TITLE
与Intave Anti Cheat的不兼容

### ISSUE THREAD

**Issue by AriaCraft2019** [Imanity-Software/ImanitySpigot3-git#115]
### Expected behavior 預期狀況

Practice服务器能正常工作，后台没有报错，服务器不会随机卡顿。

### Observed/Actual behavior 實際狀況

服务器后台的Intave反作弊存在报错，并且报错后将会出现卡顿。

### Steps/models to reproduce 重現的方式

只要Intave与Ispigot一起运行，就会随时随机报错。
以下是日志:
https://paste.imanity.dev/J07pcuT

### Plugin list 插件列表

CPS_Watcher-1.0-SNAPSHOT.jar
CrashFix-3.9.3.jar
FastAsyncWorldEdit.jar
Frost-8.7.1.jar
HolographicDisplays.jar
ImanitySpigot-v3-1.0.jar   (Frost作者提供的读取ispigot3的kb的插件)
Intave-14.4.1.jar
LiteBans.jar
LuckPerms-Bukkit-5.4.9.jar
Matrix_6.7.0_hotfix10.jar
NekoAddition-2.6.6-HOTFIX.jar
PlaceholderAPI-2.11.1.jar
PlugMan.jar
ProtocolLib.jar
PunishManager-1.3.4-NEXTGEN.jar
SuperVanish.jar
TABv3.1.0.jar
TrChat-1.90-R6.jar
Vault.jar
ViaVersion-4.2.1.jar
WorldEdit.jar
intavestorage-0.4.1-all.jar
kickall.jar

### ImanitySpigot3 的版本

2022.05.1 LTS BUILD 2

### Agreements 同意事項

- [X] 我目前運行的 ImanitySpigot3 版本在 #client-info 頻道中有顯示在 正在支援 的版本列表裡.
- [X] 我有在這個 Issue Tracker 中搜尋過並沒有發現類似的問題回報.
- [X] 我已經把原版的 TacoSpigot 1.8.8 和 ImanitySpigot3 互相比較過並且確定只有 ImanitySpigot3 會發生這個問題.

### Others 額外資訊

我们和intave作者也说过这件事情，他们说是Ispigot的区块系统的问题。

![Desktop Screenshot 2022 05 14 - 14 53 52 29](https://user-images.githubusercontent.com/82739427/168414657-9d991912-553d-4dd1-953b-8f48e0715b06.jpg)

在paperspigot中，不会出现这个报错，使用ispigot后就会有这个报错

**Comment by LeeGodSRC** [comment]
Duplicated of #121 , and #121 is more detailed
