### ISSUE TITLE
Netty patch error

### ISSUE THREAD

**Issue by Suqatri** [Imanity-Software/ImanitySpigot3-git#117]
### Stack trace

```
https://www.toptal.com/developers/hastebin/tadoyidifo.md
```

### Plugin list

no plugins

### Steps/models to reproduce (if known)

1. Download latest build (2022.05.2 LTS BUILD 3 (LATEST & RECOMMENDED))
2. Start with java 17 and enter your license 
3. Error: [https://www.toptal.com/developers/hastebin/tadoyidifo.md](https://www.toptal.com/developers/hastebin/tadoyidifo.md)

### ImanitySpigot3 version

2022.05.2 LTS BUILD 3

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

**Comment by Kydaix** [comment]
I have the same problem on my side, with Java 17 too.

**Comment by LeeGodSRC** [comment]
Fixed in **Rancha** *2022.5.1 BUILD 2*
