### ISSUE TITLE
Player random high ping

### ISSUE THREAD

**Issue by Synix99** [Imanity-Software/ImanitySpigot3-git#118]
### Expected behavior

No high ping.

### Observed/Actual behavior

Some players get a ping of 200 although they have a ping of 23 on other servers. As soon as I deactivate ImanitySpigot these players have a normal ping again.

### Steps/models to reproduce

unknown

### Plugin list

(16): Citizens (2.0.16-SNAPSHOT (build 1267)), FastAsyncWorldEdit (21.03.26-b67f782-1287-22.3.10), Arena (0.0.3-SNAPSHOT), ViaVersion (4.2.1), WorldLoader (1.1), ProtocolLib (4.7.0), ViaRewind (2.0.2), WorldEdit (6.1.9;caf0ad9), AdvancedReplay (1.8.1), AntiTAB (1.0.1), TAB (3.1.1), HolographicDisplays (2.4.6), NetworkManager (2.11.3), WorldGuard (6.1), ServerManager (1.0-SNAPSHOT), WGRegionEvents (1.1)

### ImanitySpigot3 version

2022.05.3 BUILD 1

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

**Comment by xpg-hard** [comment]
Could you please send the server logs and the log from spark. It would help us a lot

**Comment by Synix99** [comment]
https://spark.lucko.me/g7hZGTeOe8
https://www.toptal.com/developers/hastebin/nuhizexini.yaml
https://www.toptal.com/developers/hastebin/netogekico.yaml

**Comment by Synix99** [comment]
was fixed with 2022.05.1 BUILD 2
