### ISSUE TITLE
Toggle MobAI by command doesn't stop Entity from moving

### ISSUE THREAD

**Issue by kuba256** [Imanity-Software/ImanitySpigot3-git#12]
### Expected behavior

I expected that mob will dont do anything when is mob AI disabled.

### Observed/Actual behavior

Some mobs were moving.
When the bunny is jumping while performing AI command, it keeps jumping when is AI disabled.
Pig keeps walking for a while when he is walking for a carrot.

### Steps/models to reproduce

https://youtu.be/TwuvLE5i9fA

### Plugin list

Plugins (6): Crux (3.0), LuckPerms (5.3.55), spark (1.6.1), FastAsyncWorldEdit (21.03.26-b67f782-1287-22.3.10), LiteBans (2.7.5), WorldEdit (6.1.7;dd00bb1),

Crux is loader for Frost (practice plugin - https://elb1to.me/frost/)

After removing all plugins the issue was still there.

### ImanitySpigot3 version

2021.08.1 BUILD 1

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

### Other

Running Java 8

**Comment by LeeGodSRC** [comment]
After researching we realize that we completely ignores behaviour controller after AI were disabled, even stop request were being ignored
In the update **2021.08.1 BUILD 2** the problem should be fixed
Although the entity will not stop immediately, but when it finished perform their current action they will stop
