### ISSUE TITLE
加入 LagSpikeTriggerEvent

### ISSUE THREAD

**Issue by RealGoodestEnglish** [Imanity-Software/ImanitySpigot3-git#122]
### Is your feature request related to a problem? 你的問題是否與一個問題有關?

不是

### Describe the solution you'd like. 說明你的建議

這個Event 當ImanitySpigot 的Lag spike logger 偵測到有卡頓的時候就會觸發
可以讓其他伺服主即使離線的時候都可以知道伺服器卡頓, 也更方便進行更多的操作

### Describe alternatives you've considered. 你是否有想過其他的解決方法?

沒有

### Agreements 同意事項

- [X] 我已經嘗試在 Issues 中搜尋是否有人提出類似的建議
- [X] 我已經確定這個功能並沒有實裝到最新版的 ImanitySpigot3 中

**Comment by LeeGodSRC** [comment]
已在最新版本中新增
