### ISSUE TITLE
Serveur crash avec /spawn

### ISSUE THREAD

**Issue by Nishibaka** [Imanity-Software/ImanitySpigot3-git#130]
### Message d'erreur en console

https://paste.imanity.dev/N3eLgJn

### Liste des plugins

I cant send

### Etapes pour réproduire le problème (si vous le savez)

/spawn (Essentials spawn)

### ImanitySpigot3 version

2022.05.2 LTS BUILD 4

### Accords

- [X] J'utilise la dernière version d'ImanitySpigot3 disponible depuis le salon
- [X] J'ai fais des recherches afin d'être certains qu'il n'y est pas déjà une "issue" ouverte à ce sujet.
- [X] J'ai fais des comparaisons du problème entre TacoSpigot 1.8.8 et ImanitySpigot3. Et ce problème se produit seulement avec ImanitySpigot3.

**Comment by Whizyyy** [comment]
Je n'ai pas été en mesure de reproduire votre erreur. Essayez de vérifier que la version de Essentials & EssentialsSpawn soient à jours.

**Comment by LeeGodSRC** [comment]
closed due to inactivity.
