### ISSUE TITLE
Please add toggle able ping command and 1.7 legacy support

### ISSUE THREAD

**Issue by MRSgami** [Imanity-Software/ImanitySpigot3-git#131]
### Is your feature request related to a problem?

Not really I just see that these are missing that ispigot2 had so I would like to see them here as well

### Describe the solution you'd like.

Pretty easy I don't know how hard it is for you guys to code it in or add libs for it but yea. I would pretty much like to be able to turn off the ping command and have 1.7 legacy support again.

### Describe alternatives you've considered.

There are no alternatives I would consider.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest ImanitySpigot3.

**Comment by MRSgami** [comment]
And newer version support as well

**Comment by Whizyyy** [comment]
Hello, this is possible by using ViaVersion & ViaRewind. iSpigot2 were just shading these plugins, you can just put them into your plugins folder. Also ping command is customizable thanks to the premium plan.

**Comment by MRSgami** [comment]
I don't wanna pay to have to disable it
