### ISSUE TITLE
Lighting issue with loading/saving chunks.

### ISSUE THREAD

**Issue by interable** [Imanity-Software/ImanitySpigot3-git#133]
### Expected behavior

Before and after relog lighting should stay the same.

### Observed/Actual behavior

After relogging the lighting is incorrect, just look at the screenshot.

### Steps/models to reproduce

1. Teleport to coordinates outside spawn chunks.
2. Just place a block.
3. Quit from the server
4. Join to the server
5. Lighting is incorrect, its just darker than it should be

### Plugin list

none

### ImanitySpigot3 version

2022.05.3 BUILD 3

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

### Other

This bug is probably caused with loading/saving chunks because when I disable 'doChunkUnload' it works as intended.
Freshly generated configs (with fastasynclight enabled) and world.

before relog:
![image](https://user-images.githubusercontent.com/109629887/180102334-b0185c21-fbfe-4df6-b095-6c38f678996d.png)
after relog:
![image](https://user-images.githubusercontent.com/109629887/180102348-96ca0d24-84c7-499a-a64b-7edfe4c6a45b.png)

**Comment by interable** [comment]
I can also reproduce it without FastAsyncLight

**Comment by xpghard** [comment]
Do you change your gamma settings?

**Comment by interable** [comment]
No, settings are the same.

**Comment by CreaCloudz** [comment]
I carried out the test with the latest version and I still have the same light problem when I load it and reconnect the light has disappeared. I don't use FAWE I use ViaVersion and 4 other private plugins (API, HUB, Cosmetics, AC)

![2023-04-21_20 50 01](https://user-images.githubusercontent.com/12797827/233713058-6d1b2532-51dd-4d53-93b3-621bb778f72c.png)
![2023-04-21_20 50 10](https://user-images.githubusercontent.com/12797827/233713065-540b2516-64da-48d9-b8a0-b966f2ed792e.png)
