### ISSUE TITLE
Setting viewdistance to the player

### ISSUE THREAD

**Issue by Betterovsky** [Imanity-Software/ImanitySpigot3-git#135]
### Expected behavior

Use async -> p.spigot().setViewDistance(5)

Wants to set chunk generation to player
e.g. to have one player generate 3 chunks and another player generate 10 chunks

--------------
Example:
https://github.com/Wind-Development/WindSpigot/blob/master/WindSpigot-Server/src/main/java/net/minecraft/server/PlayerChunkMap.java
line 325 - 355
--------------

### Observed/Actual behavior

https://paste.imanity.dev/EAPvqlj

### Steps/models to reproduce

https://paste.imanity.dev/EAPvqlj

### Plugin list

My plugins

### ImanitySpigot3 version

2022.05.3 BUILD 4

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

**Comment by LeeGodSRC** [comment]
You are NOT supposed to call it async. it's not thread-safe

**Comment by LeeGodSRC** [comment]
Then you should made feature request instead. such as setViewDistanceAsync()

**Comment by LeeGodSRC** [comment]
I mean, make a feature request.
