### ISSUE TITLE
Async setting viewdistance to the player

### ISSUE THREAD

**Issue by Betterovsky** [Imanity-Software/ImanitySpigot3-git#136]
### Is your feature request related to a problem?

Yes. 
Described all here: 
https://github.com/Imanity-Software/ImanitySpigot3-git/issues/135#issuecomment-1202670417

### Describe the solution you'd like.

API that would be responsible for changing such values pespersonally for the player, we want to make settings in which the player will be able to modify these values.

(@LeeGodSRC You are NOT supposed to call it async. it's not thread-safe use p.spigot().setViewDistance(5))
- Chunk generation distance  (p.spigot().setViewDistance(5) -> p.spigot().setViewDistanceAsync(5))

### Describe alternatives you've considered.

API that would be responsible for changing such values pespersonally for the player, we want to make settings in which the player will be able to modify these values.

- Viewing distance of players TODO
- Viewing distance of monsters TODO
- Viewing distance of animals TODO
- Viewing distance of various creatures TODO
- Distance of seeing particles TODO
- Viewing distance of other beings TODO

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest ImanitySpigot3.

**Comment by LeeGodSRC** [comment]
Have you even tried to use setViewDistance under ImanitySpigot3? due to the structure design by ImanitySpigot, setViewDistance are not suppose to make server lag a lot.

**Comment by LeeGodSRC** [comment]
Can you provide a spark report when delay happens?

**Comment by xpghard** [comment]
No respond.
