### ISSUE TITLE
Issue with Bow Knockback

### ISSUE THREAD

**Issue by Whizyyy** [Imanity-Software/ImanitySpigot3-git#139]
### Expected behavior

I should not move at all when I puch myself with the bow.

### Observed/Actual behavior

I am taking a lot of knockback.

### Steps/models to reproduce

https://user-images.githubusercontent.com/47752694/183292401-7c2dcd48-cd87-42f4-be26-1b7c66a2cddd.mp4

![image](https://user-images.githubusercontent.com/47752694/183292416-32763787-e156-4752-a15c-8babfe702a28.png)

### Plugin list

spark

### ImanitySpigot3 version

2022.05.3 BUILD 4

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

**Comment by LeeGodSRC** [comment]
What's the v2 module you were using?

**Comment by Whizyyy** [comment]
Yes

**Comment by LeeGodSRC** [comment]
I'm unable to reproduce it, are you sure you linked the profile to the player, or set the kb to default yet?
