### ISSUE TITLE
Disable limit of characters

### ISSUE THREAD

**Issue by Betterovsky** [Imanity-Software/ImanitySpigot3-git#143]
### Describe the solution you'd like.

Possibility to disable in config characters limitation below screen from engine

The issue is what about the function upTo256CharsInChat option:
``By default in minecraft you can only send messages of 100 characters in chat.
But many modified clients allow you to send more.
Enabling this option will allow clients to send messages with a 256 character limit instead of 100.
``

![image](https://user-images.githubusercontent.com/89166198/184493678-7cb1bcaa-ebd1-40a5-a6bb-e1e1fc25c4ac.png)

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest ImanitySpigot3.

**Comment by Whizyyy** [comment]
This option "upTo256CharsInChat" has been created because some popular clients could stand to have more, I don't think that's the case for what you are asking. Removing this limit would simply risk bugs with the clients.
