### ISSUE TITLE
InstantRespawn function error

### ISSUE THREAD

**Issue by Betterovsky** [Imanity-Software/ImanitySpigot3-git#144]
### Expected behavior

No death screen after using player.setHealth(0.0); 

### Observed/Actual behavior

After using this: player.setHealth(0.0); and with the function enabled 'instantRespawn: true' instantrespawn not working

### Plugin list

My plugins

### ImanitySpigot3 version

spigotJarVersion: 2022.05.3 BUILD 4

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

**Comment by xpghard** [comment]
I have repeated the bug. Here the video that it occurs.
https://youtu.be/fFSNm1Bq0MQ
