### ISSUE TITLE
Double hits 

### ISSUE THREAD

**Issue by bartiiix** [Imanity-Software/ImanitySpigot3-git#145]
### Expected behavior
Use java 17 !!!!
EntityDamageByEntityEvent - No possibility of duplicating an event by quickly changing slots in the inventory.

### Observed/Actual behavior
Use java 17 !!!!

1) EntityDamageByEntityEvent - When switching slots in an inventory very quickly, e.g. 1 slot to 2 slots and then 2 slots to 1 slot. The event is executed several times faster than it should be. When collecting data through this event players take advantage of this and have much more data than they should have. 

### Steps/models to reproduce

Nothing

### Plugin list

My plugins

### ImanitySpigot3 version

spigotJarVersion: 2022.05.3 BUILD 4

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

**Comment by xpghard** [comment]
1. Bug with giving the name of the wrong item. I am unable to reproduce this after many attempts.
2.After writing a macro that changes slots between 1 and 2 and hits the player, it can be observed that it pulls the player towards the ground terribly and the hits do not change much.
https://youtu.be/2BW3eVtlb7Y

**Comment by xpghard** [comment]
Update on this case. When beating a player normally the delay between player hits works normally between 500-550, but when I turn on the macro that changes between slots 1 and 2 you can see delays between hits of up to 150. Below I attach the code used for this tes
![Bez nazwy](https://user-images.githubusercontent.com/100840109/185097635-43de5e64-37d8-413c-8db0-c65fc75c30d4.png)
t.

public class EntityDamageListener implements Listener {

    private final HashMap<UUID, Long> hits = new HashMap<>();

    @EventHandler
    public void onDamage(EntityDamageByEntityEvent event) {
        if (!(event.getDamager() instanceof Player))
            return;

        Player player = (Player) event.getDamager();

        Long lastHit = hits.getOrDefault(player.getUniqueId(), -1L);

        hits.put(player.getUniqueId(), System.currentTimeMillis());

        if (lastHit == -1)
            return;

        player.sendMessage("Ostatni czas od hitu: " 
                + (System.currentTimeMillis() - lastHit));

    }


}

**Comment by Whizyyy** [comment]
Can you show the debug result with a normal tacospigot please

**Comment by xpghard** [comment]
> Can you show the debug result with a normal tacospigot please

Could you provide the version that ispigot uses or send a link? The only one I have found is tacospigot which uses bilbiots which do not exist.

**Comment by xpghard** [comment]
> Can you show the debug result with a normal tacospigot please

![image](https://user-images.githubusercontent.com/100840109/185275695-2bc8e219-1ef5-4a6a-8610-9eaee0a88017.png)
same.  Only problem is that taco spigot has not been updated since 2017

**Comment by xpghard** [comment]
@Betterovsky After two days of testing, I found that, regardless of whether one changes slots or not, the hits are the same. So the question is where did the pseudo combo hits in the picture come from? It turns out that minecraft in defaults has this at criticals damage. I consider the thread to be closed. 

Is there anything else we can help with?
