### ISSUE TITLE
AsyncChat

### ISSUE THREAD

**Issue by xpghard** [Imanity-Software/ImanitySpigot3-git#146]
### Is your feature request related to a problem?

My feature request is not a problem

### Describe the solution you'd like.

I believe it is an option that should be there because it is even on newer versions (1.17+ and above).

### Describe alternatives you've considered.

.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest ImanitySpigot3.

**Comment by wuangg** [comment]
Chat is already being handled in asynchronous anyway, except for commands

**Comment by xpghard** [comment]
My programmer made a mistake
