### ISSUE TITLE
Eat and drop bug

### ISSUE THREAD

**Issue by xpghard-zz** [Imanity-Software/ImanitySpigot3-git#147]
### Expected behavior

![image](https://user-images.githubusercontent.com/100840109/185265363-cfef4a61-fdf4-4f95-bcb3-a2d0fcf0acdb.png)
I would like that when the player walks forward and clicks right and throws the food away (1 time, quick click) he doesn't eat it after 1 second.

moreover, it works regardless of whether this option is enabled

### Observed/Actual behavior

When I go forward and click quickly right on the food and at the same time throw it away it will be eaten without the food animation.

### Steps/models to reproduce

https://youtu.be/iStvFsGagjc
watch this :O

### Plugin list

0 plugins

### ImanitySpigot3 version

2022.05.2 LTS BUILD 4

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

**Comment by LeeGodSRC** [comment]
The video is no longer playable, can you reupload it or something?

**Comment by xpghard** [comment]
Can't reproduce
