### ISSUE TITLE
Rancha Version Upgrade Warn and Waiting Time

### ISSUE THREAD

**Issue by ZeyKoYT** [Imanity-Software/ImanitySpigot3-git#15]
### Is your feature request related to a problem?

Rancha version warning take to much time before lunching the jar. 

### Describe the solution you'd like.

It will be nice if there is an setting to disable version upgrade warning of Rancha , because it take some times to start the server (10s) and for developers it's a bit boring ^^ 

### Describe alternatives you've considered.

Add and setting to disable updateCheck
or add an setting to disable updateCheck waiting time 

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest ImanitySpigot3.

**Comment by Whizyyy** [comment]
If you are a developer, why are you not using the latest version of Rancha to avoid this warning?

**Comment by LeeGodSRC** [comment]
In Rancha **2021.11.1 LTS BUILD 1** or above it's not longer an issue
