### ISSUE TITLE
ServerHitDetection

### ISSUE THREAD

**Issue by xpghard-zz** [Imanity-Software/ImanitySpigot3-git#152]
### Is your feature request related to a problem?

Kind of feature

### Describe the solution you'd like.

I would like there to be an api for serverhitdetection(and for it to finally come out of beta)
The api would be to add an option to set the player range and disable serverhitdetection for a player.

### Describe alternatives you've considered.

.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest ImanitySpigot3.

**Comment by Xefreh** [comment]
ServerSideHitDetection has been removed.
