### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Sushirod** [Imanity-Software/ImanitySpigot3-git#153]
### Stack trace

```
https://paste.imanity.dev/nqjxHRW
```

### Plugin list

LuckPerms (5.4.41),
 DN-GiveAddon-HD (2.0)
spark (1.9.25)
LPX (3.1.4)
 MinecubCoreHD (1.0-BETA)
Sparky (1.2)
SistemaNivelesMC (1.0)
DestruyeElNexo (3.5)
PlayerReset (1.7)
WorldRestorer (1.0.0)
AdvancedSystemClan (1.0)

### Steps/models to reproduce (if known)

Dont Know

### ImanitySpigot3 version

spigotJarVersion: 2022.08.1 BUILD 1

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue between TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occurred this issue.

### Other

Help Us! We think is a crasher

**Comment by Sushirod** [comment]
Update of the problem:

When a vector gets Nan the hole server crashes, adding velocity or sth 

If vector gets Nan crashes

**Comment by xpghard** [comment]
> Update of the problem:
> 
> When a vector gets Nan the hole server crashes, adding velocity or sth
> 
> If vector gets Nan crashes

Can you show code?

**Comment by Xayanix** [comment]
Its vanilla bug btw.
