### ISSUE TITLE
Redstone Plane Bug

### ISSUE THREAD

**Issue by xpghard-zz** [Imanity-Software/ImanitySpigot3-git#154]
### Expected behavior

I tried to make an aeroplane from this video but after the last update it completely broke down.
https://youtu.be/KN-lcQT85xs

### Observed/Actual behavior

https://youtu.be/8hfBL2PTkFo

### Steps/models to reproduce

.

### Plugin list

0

### ImanitySpigot3 version

2022.08.1 BUILD 2

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue between TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occurred this issue.

**Comment by Whizyyy** [comment]
Can you try to disable option `betterRedstoneAlgorithm` and see if the issue is still happening?

**Comment by xpghard** [comment]
> Can you try to disable option `betterRedstoneAlgorithm` and see if the issue is still happening?

Working fine
![image](https://user-images.githubusercontent.com/100840109/189520310-ad955eeb-8433-4dc6-b875-a6a8f83e788f.png)

**Comment by LeeGodSRC** [comment]
Since algorithm is different, some redstone MAY break with the "betterRedstoneAlgorithm" in the spigot. so we'd suggest any server using heavy redstone mechanic disable it.
