### ISSUE TITLE
Cannons not working

### ISSUE THREAD

**Issue by Redwolf223** [Imanity-Software/ImanitySpigot3-git#158]
### Expected behavior

For the cannons to shoot without breaking.

### Observed/Actual behavior

https://drive.google.com/file/d/1S5L3J-gw_qc01wSflUnuPzQeUuSAu5y9/view?usp=sharing

This is a video of what is currently happening.

The sand seems to not work properly.

### Steps/models to reproduce

https://cdn.discordapp.com/attachments/1017538501140562001/1017551088775331901/VV_Small_cannon.schematic

You can use this schematic to test the cannon.

### Plugin list

https://drive.google.com/file/d/1UP2GuZy-a1GVpFpB17r1eo2wCbb1PUHj/view?usp=sharing

### ImanitySpigot3 version

ver 2022.8.1

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue between TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occurred this issue.

**Comment by LeeGodSRC** [comment]
Can you attach the schematic again? the link seems to be broken

**Comment by Redwolf223** [comment]
https://drive.google.com/file/d/1Yce_DdzB6y9vIOxH4LCvrJKTX1MlsEi8/view?usp=sharing

@LeeGodSRC , sure let me know if this works.

**Comment by xpghard** [comment]
@Redwolf223 This schematic is wrong? And what type of schema it is?
![image](https://user-images.githubusercontent.com/121050315/210618117-b4979f68-a29c-4c4c-82e1-6f8d82dc4f84.png)

**Comment by Redwolf223** [comment]
You need to paste it at bedrock level. It's a Y1 cannon, i'm sorry for not having specified that before.

@xpghard

**Comment by LeeGodSRC** [comment]
@xpghard

**Comment by Redwolf223** [comment]
Hi, any news? Thank you

**Comment by xpghard** [comment]
@Redwolf223 i have problem with your canon. By my side i have no idea how this should work. Can you open ticket on our discord? https://discord.com/invite/T22sDC4dUK

**Comment by LeeGodSRC** [comment]
Closed for long inactivity
