### ISSUE TITLE
AsyncMovementHandler

### ISSUE THREAD

**Issue by xpghard-zz** [Imanity-Software/ImanitySpigot3-git#159]
### Is your feature request related to a problem?

Feature Request

### Describe the solution you'd like.

A friend of mine wrote an option to register movment in async which makes the server run much more efficiently as well as canceling moving in a particular direction works much better virtually instantaneously. I think this is something that should be included.

### Describe alternatives you've considered.

.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest ImanitySpigot3.

**Comment by LeeGodSRC** [comment]
IMO async processing for movement handler should be done manually by in your code rather than have it support in spigot, it's kinda unnecessary for spigot to do it while you already have bukkit scheduler to post into async thread easily.
