### ISSUE TITLE
Server crashed when ticking world

### ISSUE THREAD

**Issue by EmptyIrony** [Imanity-Software/ImanitySpigot3-git#162]
### Stacktrace 堆疊追蹤

```
請貼上你的堆疊追蹤或是貼到 https://paste.imanity.dev/ 往站上!
```
https://paste.imanity.dev/zEJE456

### Plugin list 插件列表

Plugins: { LuckPerms v5.1.55 me.lucko.luckperms.bukkit.LPBukkitBootstrap [Luck], Adyeshach v1.5.12 ink.ptms.adyeshach.taboolib.platform.BukkitPlugin [坏黑, Arasple, zhanshi123], FastAsyncWorldEdit v19.11.13-5505943-1282-22.3.5 com.boydti.fawe.bukkit.BukkitMain [Empire92], KilledEffect v1.0 me.ram.killedeffect.Main [Ram], OpenInv v2.3.4 com.lishid.openinv.OpenInv [lishid], PlaceholderAPI v2.9.1 me.clip.placeholderapi.PlaceholderAPIPlugin [[extended_clip]], Stp v1.0 stp.Stp [], DeluxeMenus v1.10.2 me.clip.deluxemenus.DeluxeMenus [extended_clip], SQLibrary v7.1 lib.PatPeter.SQLibrary.SQLibrary [PatPeter], SpigotGuard v3.9.12 BULLET-PROOF xyz.yooniks.spigotguard.SpigotGuardPlugin [yooniks, yooniks], spark v1.9.9 me.lucko.spark.bukkit.BukkitSparkPlugin [Luck], PlayerPoints v2.1.8-DEV org.black_ixx.playerpoints.PlayerPoints [Black_ixx], Lores v1.4.1 com.codisimus.plugins.lores.Lores [Codisimus], ProtocolLib v4.6.0 com.comphenix.protocol.ProtocolLib [dmulloy2, comphenix], WorldEdit v6.1.1-SNAPSHOT;3482-867e59b com.sk89q.worldedit.bukkit.WorldEditPlugin [], Vulcan v2.6.9 me.frep.vulcan.spigot.VulcanPlugin [frep, GladUrBad, Joshb_, Elevated, retrooper], HyCraftCore v1.0-SNAPSHOT cn.hycraft.core.hycraftcore.HyCraftSpigotCore [EmptyIrony], HyCraftDrawsPlus v1.0.0 HyCraftDrawsPlus.HyCraftDrawsPlus [HyCraft], TrHologram v1.11 me.arasple.mc.trhologram.TrHologram [], HyCraftSkyPVPRank v1.0.0 HyCraftSkyPVPRank.HyCraftSkyPVPRank [HyCraft], ThePit v${project.version} cn.charlotte.pit.ThePit [EmptyIrony, Misoryan], SuperVanish v6.2.6 de.myzelyam.supervanish.SuperVanish [MyzelYam],}

### Steps/models to reproduce 重現的方式 (如果你知道怎麼重現的話)

暂时不知道如何复现, 随机出现

### ImanitySpigot3 的版本

2022.11.1 LTS BUILD 1

### Agreements 同意事項

- [X] 我目前運行的 ImanitySpigot3 版本在 #imanityspigot 頻道中有顯示在 正在支援 的版本列表裡.
- [X] 我有在這個 Issue Tracker 中搜尋過並沒有發現類似的問題回報.
- [X] 我已經把原版的 TacoSpigot 1.8.8 和 ImanitySpigot3 互相比較過並且確定只有 ImanitySpigot3 會發生這個問題.

### Others 額外資訊

有可能是我们插件代码的原因，因为近期才出现，但是不知道如何去定位

**Comment by xpghard** [comment]
@EmptyIrony 没有插件也会出现这种问题吗？?

**Comment by EmptyIrony** [comment]
@xpghard 不好意思，因为这个issue有点久了。在这期间，我们测试了确实是自己写的插件的问题，但是还暂时无法定位到底是什么代码导致的，不是iSpigot问题

**Comment by xpghard** [comment]
@EmptyIrony 所以我理解为问题不再存在，我可以关闭该票据？
