### ISSUE TITLE
Durability update 

### ISSUE THREAD

**Issue by GHSOT3R** [Imanity-Software/ImanitySpigot3-git#163]
### Votre suggestion est-elle liée à un problème ?

Oui il y a un soucis sur la durabilité on peut gèrer la durabilité en général et si l'on souhaite avoir un type de durabilité spécifique sur les armures cela va aussi impacté les items comme pioche, épée, arc, ... Et pour les paramètres que j'ai mis les pioche, épée, arc, ... ne perdes plus de durabilité alors que les armures sont parfaits. Est il possible de créer un système de whitelist ou only Armor dans la config .

### Décrivez la solution que vous aimeriez

Est il possible de créer un système de whitelist ou only Armor dans la config .

### Décrivez les alternatives que vous avez considérées

Une update plus tôt simple a réalisé qui fera plaisir a la communauté et peux incité à acheter pour certains.

### Accords

- [X] J'ai cherché et vérifié qu'il n'y ai pas d'autre "issue" à propos de ceci.
- [X] J'ai cherché et vérifié que cette fonctionnalité n'est pas déjà présente dans ImanitySpigot3.

**Comment by GHSOT3R** [comment]
@LeeGodSRC do you think that possible ?

**Comment by xpghard** [comment]
Le sujet de ce ticket est le même que celui de #167  , donc je ferme ce ticket et vous invite à celui-là.
