### ISSUE TITLE
Désactiver une Commande

### ISSUE THREAD

**Issue by Flash303** [Imanity-Software/ImanitySpigot3-git#165]
### Votre suggestion est-elle liée à un problème ?

Pouvoir désactiver les commandes (/ping par exemple) pour pouvoir les remplacer pas de commandes customs.

### Décrivez la solution que vous aimeriez

Pouvoir désactiver les commandes de imanity qui ne change rien à sont fonctionnemet.

### Décrivez les alternatives que vous avez considérées

Pouvoir avec l'api changer ces commandes

### Accords

- [X] J'ai cherché et vérifié qu'il n'y ai pas d'autre "issue" à propos de ceci.
- [X] J'ai cherché et vérifié que cette fonctionnalité n'est pas déjà présente dans ImanitySpigot3.

**Comment by xpghard** [comment]
Malheureusement, cette option n'est disponible que dans la version premium, et ne sera pas ajoutée à la licence normale. Vous pouvez acheter votre propre plugin, ou essayer d'écrire votre propre plugin qui bloque cela.
