### ISSUE TITLE
Discord cannot join: Invalid Invite Links

### ISSUE THREAD

**Issue by Yurinann** [Imanity-Software/ImanitySpigot3-git#169]
### Expected behavior 預期狀況

i can join the discord and buy the imanity spigot!

### Observed/Actual behavior 實際狀況

i cannot join the discord, it told me that a invalid invite link (may i dont have permission)

### Steps/models to reproduce 重現的方式

https://support.discord.com/hc/en-us/articles/360001556852

### Plugin list 插件列表

null

### ImanitySpigot3 的版本

null

### Agreements 同意事項

- [X] 我目前運行的 ImanitySpigot3 版本在 #imanityspigot 頻道中有顯示在 正在支援 的版本列表裡.
- [X] 我有在這個 Issue Tracker 中搜尋過並沒有發現類似的問題回報.
- [X] 我已經把原版的 TacoSpigot 1.8.8 和 ImanitySpigot3 互相比較過並且確定只有 ImanitySpigot3 會發生這個問題.

### Others 額外資訊

null

**Comment by Kydaix** [comment]
Is this link working? https://discord.gg/5V57NHjwDU

**Comment by Yurinann** [comment]
Yes, it works!
