### ISSUE TITLE
[Question] Add JPA dependency?

### ISSUE THREAD

**Issue by Yurinann** [Imanity-Software/ImanitySpigot3-git#171]
### Expected behavior 預期狀況

Plugins need JPA can run successfully.

### Observed/Actual behavior 實際狀況

Now some plugins need JPA dependency to run, but we don't have it. I can't add it on plugins that not my own.

### Steps/models to reproduce 重現的方式

Load Plugin.

### Plugin list 插件列表

My own plugin: ThePit
Another plugin: HubParkour

### ImanitySpigot3 的版本

2022.11.1 LTS BUILD 3

### Agreements 同意事項

- [X] 我目前運行的 ImanitySpigot3 版本在 #imanityspigot 頻道中有顯示在 正在支援 的版本列表裡.
- [X] 我有在這個 Issue Tracker 中搜尋過並沒有發現類似的問題回報.
- [X] 我已經把原版的 TacoSpigot 1.8.8 和 ImanitySpigot3 互相比較過並且確定只有 ImanitySpigot3 會發生這個問題.

**Comment by LeeGodSRC** [comment]
Adding dependency to spigot isn't really a good practice imo, if you can't add them to the plugin it self, how about creating an external plugin and shade the dependency in?

**Comment by Yurinann** [comment]
> Adding dependency to spigot isn't really a good practice imo, if you can't add them to the plugin it self, how about creating an external plugin and shade the dependency in?

Yes, it may be a solution. Create this issue's reason is that original spigot has this dependency for developers, but external plugin is also another solution, im going to try it, thanks!

**Comment by Yurinann** [comment]
> Adding dependency to spigot isn't really a good practice imo, if you can't add them to the plugin it self, how about creating an external plugin and shade the dependency in?

And if you agree this solution, this issue can be closed, thanks!

**Comment by xpghard** [comment]
@LeeGodSRC
