### ISSUE TITLE
ArmorStand customname and visibility

### ISSUE THREAD

**Issue by CyriacF** [Imanity-Software/ImanitySpigot3-git#177]
### Expected behavior

Text and animation with armor stand with customname and not visible

### Observed/Actual behavior

The farthest armor stands appear empty, visible and without custom name, after a right click, the text reappears and the armor stand is hidden

### Steps/models to reproduce

With spigot, create an armor stand, put a custome name and make it invisible, like for generators in bedwars
Once done, tp a person far enough from the armor stand, and with a little luck it appears visible and without custom name

### Plugin list

BedWars1058
SlimeWorldManager
ViaVersion
Protocollib
Luckperms
PremiumVanish

### ImanitySpigot3 version

2022.11.1 LTS BUILD 3

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue between TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occurred this issue.

### Other

I have tested all config and issue continue to happend, maybe is SWM and world option idk ?

**Comment by SiriHackYT** [comment]
https://i.imgur.com/rjVPWzH.png

**Comment by SiriHackYT** [comment]
And sometimes diamond lootin in generator drop a stone https://i.imgur.com/pwa0H2N.png

**Comment by LeGnRal** [comment]
i have the same problem here

**Comment by KataNF** [comment]
@LeeGodSRC I can confirm that issue. ProtocolLib v5.0 support for ImanitySpigot is broken (v4.8 works great), also NPCs created in Citizens sometimes spawns without armor.

**Comment by LeeGodSRC** [comment]
> @LeeGodSRC I can confirm that issue. ProtocolLib v5.0 support for ImanitySpigot is broken (v4.8 works great), also NPCs created in Citizens sometimes spawns without armor.

It'd be better if you can create an issue that describe more details about the ProtocolLib issue
