### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by Shzv** [Imanity-Software/ImanitySpigot3-git#178]
### Expected behavior

I would like to understand if it is a bug, because I tried to execute the /tp coordinates command with plugins and without plugins but the visual is bugged as in the video

### Observed/Actual behavior

when I go to execute the command /tp coordinates the view is bugged as in the video

### Steps/models to reproduce

https://i.imgur.com/MiyLXJ2.mp4 

### Plugin list

eden fawe protocollib placeholder worldedit all viaversio plugin 

### ImanitySpigot3 version

2022.11.1 LTS BUILD 3 VERSION JAVA 8 

### Agreements

- [x] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue between TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occurred this issue.

### Other

but even without plugins the same problem occurred.
I started having this problem since I bought ispigot

**Comment by ItsClairton** [comment]
Same problem here

**Comment by LeeGodSRC** [comment]
If I remember correctly this seems to be a client bug rather than server side bug
