### ISSUE TITLE
Discord invite link doesn't work

### ISSUE THREAD

**Issue by Xayanix** [Imanity-Software/ImanitySpigot3-git#179]
### Expected behavior

Discord invite link doesn't work

### Observed/Actual behavior

Discord invite link doesn't work

### Steps/models to reproduce

Discord invite link doesn't work

### Plugin list

Discord invite link doesn't work

### ImanitySpigot3 version

Discord invite link doesn't work

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue between TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occurred this issue.

### Other

Discord invite link doesn't work

**Comment by LeeGodSRC** [comment]
Hello, can you tell us where is the link that is broken?

**Comment by Xayanix** [comment]
At website - imanity.dev

![image](https://user-images.githubusercontent.com/12672902/219972331-6d519e20-9b5a-4ff7-9e4f-75252d9d1b13.png)
