### ISSUE TITLE
TNT are not moved by water when activated

### ISSUE THREAD

**Issue by Hoknyy** [Imanity-Software/ImanitySpigot3-git#181]
### Expected behavior

When I activate TNT in flowing water, it doesn't move. So it makes TNT cannons kind of not usefull.

### Observed/Actual behavior

Hi !

I have the latest version of Immanity on my faction server. I have a little issue : the tnt are not moved by the water. I tried with a regular paper.jar and this fix that. I have tried some modification on the imanity config but I didn't manage to fix this. Do you have any idea to fix this ?

### Steps/models to reproduce

Put water and tnt next to it (like for a tnt cannon). Then, activate the TNT.

### Plugin list

https://prnt.sc/zL4_E62TYpeM https://prnt.sc/QdDDATisWuVV https://prnt.sc/8JgckL-C8ZfC

### ImanitySpigot3 version

[2023.2.1 LTS BUILD 2] - 2023-February-18

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue between TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occurred this issue.

### Other

config.yml https://code.imanity.dev/FYw9g1s 
default.yml https://code.imanity.dev/WVCe7xC (same as the world.yml)

**Comment by xpghard** [comment]
After testing with your config and default config, i can't reproduce issue. Can you check if issue is caused by your plugins? And if you can send video about this?

**Comment by LeeGodSRC** [comment]
@Hoknyy
