### ISSUE TITLE
kick problem 

### ISSUE THREAD

**Issue by haroldrc** [Imanity-Software/ImanitySpigot3-git#182]
### Expected behavior

Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 0/75 (ClientboundSetChunkCacheCenterPacket) was larger than I expected, found 51 bytes extra whilst reading packet 75

### Observed/Actual behavior

Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 0/75 (ClientboundSetChunkCacheCenterPacket) was larger than I expected, found 51 bytes extra whilst reading packet 75

### Steps/models to reproduce

enter the 1.8 server with the 1.19 client

### Plugin list

![image](https://user-images.githubusercontent.com/29206120/221873104-9d2c4664-fdca-4f9e-9003-a879927d5abb.png)

### ImanitySpigot3 version

2023.02.1 LTS BUILD 1

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue between TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occurred this issue.

**Comment by xpghard** [comment]
@haroldrc as far as I can see, this is a viaversion problem. Are you sure this problem does not occur on paper spigot?

**Comment by LeeGodSRC** [comment]
@haroldrc

**Comment by Xefreh** [comment]
Issue closed. customer could not provide details if the issue existed on paper.
