### ISSUE TITLE
Make it so you can bow someone while they are being hit in the same tick please

### ISSUE THREAD

**Issue by KonMD** [Imanity-Software/ImanitySpigot3-git#183]
### Is your feature request related to a problem?

I want this added so when someone is fighting someone another player can bow them as seen in this short little video i clipped. 

https://cdn.discordapp.com/attachments/1082131803663515689/1082133449290301550/Base_Profile_2023.03.05_-_20.44.31.04.DVR.mp4 - all you need to do is I belive is to allow the player to be damaged in that same tick it's in most HCF spigot's that people use for their servers like vortex spigot, aSpigot by scale (foxspigot,pSpigot,wSpigot,mSpigot) and a lot of other spigots.

### Describe the solution you'd like.

Just make it so the player can be damaged twice in the same tick (https://media.discordapp.net/attachments/932250656260108319/952453715699306526/unknown.png?width=878&height=141)

### Describe alternatives you've considered.

idk any

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest ImanitySpigot3.

**Comment by LeeGodSRC** [comment]
can you show us an example of how a working spigot fork should act on this?

**Comment by LeeGodSRC** [comment]
@StreetSigns

**Comment by LeeGodSRC** [comment]
Duplicates of #201
