### ISSUE TITLE
'processPacketWhileSleeping' not working at all.

### ISSUE THREAD

**Issue by interable** [Imanity-Software/ImanitySpigot3-git#185]
### Expected behavior

option should work as intended

### Observed/Actual behavior

not working at all

### Steps/models to reproduce

change 'processPacketWhileSleeping' results in no change at all

### Plugin list

none

### ImanitySpigot3 version

2023.02.1 LTS BUILD 6

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue between TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occurred this issue.

**Comment by LeeGodSRC** [comment]
Hey, as we changed the algorithm of the spigot, packets now always attempts to process while thread sleeping even if the option is off.
