### ISSUE TITLE
Add an argument to define explosion damage

### ISSUE THREAD

**Issue by louseee** [Imanity-Software/ImanitySpigot3-git#188]
### Is your feature request related to a problem?

No.

### Describe the solution you'd like.

I would like an argument in the createExplosion method to define the damage of the explosion to entities.

### Describe alternatives you've considered.

+
None of them actually work properly.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest ImanitySpigot3.

**Comment by xpghard** [comment]
I don't think it's a good idea for there to be constant damage to the setting. You can get this with a simple plugin that requires from 10 lines. Example below.
https://bukkit.org/threads/setting-damage-of-an-explosion.348628/
Besides, the default damage is variable and depends on many factors. The only thing that makes sense is a tnt damage multiplier.

**Comment by louseee** [comment]
But maybe add an option to disable damage with AsyncExplosion ? Because I would like to damage players by my self in my own plugin, not with default damage of the explosion. 
My explosion is created by a spell and I would like to use Async Explosion to create this one but without damaging players near.

**Comment by xpghard** [comment]
@louseee wouldn't it be better if there was an api to configure the whole tnt mechanism as there is with a normal burst?

**Comment by Xefreh** [comment]
Issue closed. Invalid format
