### ISSUE TITLE
Removing entity when there's no player around this entity. 

### ISSUE THREAD

**Issue by Adriuoda** [Imanity-Software/ImanitySpigot3-git#192]
### Expected behavior

entity gets removed, either there's a player around it or not.

### Observed/Actual behavior

entity gets removed when there's player around this entity, but when there's not, it doesn't remove this entity.

### Steps/models to reproduce

Spawn the entity.
Teleport any near player away far from this entity.
then after 4 seconds remove the entity using Entity#remove.

### Plugin list

![Screenshot_20230410_122845](https://user-images.githubusercontent.com/53695565/230795028-2f5500a6-70f2-4968-af9f-7eaa6232d312.png)

### ImanitySpigot3 version

2023.03.1 BUILD 2

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue between TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occurred this issue.

### Other

I'm not sure about it but might it be from the chunks? maybe.

**Comment by Adriuoda** [comment]
`        for (Entity droppedItem : droppedItems) {
            if (droppedItem != null && !droppedItem.isDead()) {
                droppedItem.getWorld().imanity().getChunkAtAsynchronously(droppedItem.getLocation(), AsyncPriority.NORMAL).thenAccept(chunk -> {
                    if(!chunk.isLoaded()) {
                        chunk.load();
                        System.out.println("Loadded chunk!");
                    }
                    for (Entity entity : chunk.getEntities()) {
                        if(entity.getEntityId() == droppedItem.getEntityId()) {
                            entity.remove();
                            System.out.println("REMOVED: " + entity.getType().name());
                        }
                    }
                });
            }
        }`
        based on what i've read on the documents, i loaded the chunk asynchronously, so i can remove the entity, but the entity isn't getting removed.

**Comment by interable** [comment]
that's totally normal and expected behaviour, to solve your problem you need to remove entities when chunk is unloading.
Your actual code cause memory leak, because when chunk is unloaded you store Entity objects, which cause to garbage collector not remove them.
Code that you pasted is not working because entity id is not stored in nbt, rather is used for identify loaded entities, it's impossible for entity's to have same id, so when chunk unloads and load again id's for entities in this chunk are different

**Comment by Adriuoda** [comment]
Got it! thanks!
