### ISSUE TITLE
Ender Pearl cooldown

### ISSUE THREAD

**Issue by FixYourWork** [Imanity-Software/ImanitySpigot3-git#194]
### Is your feature request related to a problem?

It would be nice if we can set ender pearl cooldown.

### Describe the solution you'd like.

EnderPearlCooldown option in \imanityconfig.

### Describe alternatives you've considered.

I tried every option in imanityspigot3 configs.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest ImanitySpigot3.

**Comment by LeeGodSRC** [comment]
I'm not exactly sure if it's a good idea to add ender pearl cooldown inside of a spigot rather than on a plugin but I will keep it here for now

**Comment by Xefreh** [comment]
Issue closed, this feature has to be made in a custom plugin.
