### ISSUE TITLE
Spigot launcher crash on license verification

### ISSUE THREAD

**Issue by Mandress101** [Imanity-Software/ImanitySpigot3-git#197]
### Stack trace

```
https://code.imanity.dev/XahTMwA
```

### Plugin list

Spark

### Steps/models to reproduce (if known)

Idk, i simply started the launcher

### ImanitySpigot3 version

2023.03.1 BUILD 3

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue between TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occurred this issue.

### Other

I'm using the jar on windows

**Comment by LeeGodSRC** [comment]
https://docs.imanity.dev/imanityspigot/troubleshooting#file-encoding
