### ISSUE TITLE
ProtocolLib v5.0 doesn't work propertly on ImanitySpigot

### ISSUE THREAD

**Issue by evolvex3** [Imanity-Software/ImanitySpigot3-git#198]
### Expected behavior

Server proper work on ProtocolLib (v5.0) as same as on (v4.8)

### Observed/Actual behavior

When player are joining server or gets in chunk where are some entities, sometimes it is possible for entities to don't have some armor pieces.
I made a debug code, and listened to packets throught protocollib, and what I observed is that on v5.0 version packets are not always
send chronically (so equipment packet can be sent before a spawning one) and are always send on Server Thread, on v4.8 they are always chronically and I noticed some packets
was sent from ImanitySpigot entity trackers thread. It is probably caused due to v5.0 protocol injection code rewrite (https://github.com/dmulloy2/ProtocolLib/pull/1524)
Debug logs (Packet Type/Entity ID/Current Thread):
v5.0: https://paste.imanity.dev/LWYZhpj
v4.8: https://paste.imanity.dev/3SP1NA8

### Steps/models to reproduce

Written above

### Plugin list

ProtocolLib (v5.0)
Citizens

### ImanitySpigot3 version

2023.03.1 BUILD 3

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue between TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occurred this issue.

**Comment by ClutchxUserFS** [comment]
Happens to me too w/ protocol 5.0!

**Comment by Xefreh** [comment]
issue is caused by imanity async entity tracker, you can disable it until a fix is found.

**Comment by KataNF** [comment]
ProtocolLib v5.0 has been oficially released today. When making that issue it was on SNAPSHOT stage, but official release didn't change anything in this problem. @LeeGoodSRC is there any chance to that be fixed? I don't want to disable async entity trackers due to performance decrease.
