### ISSUE TITLE
Bedrock Edition support issues

### ISSUE THREAD

**Issue by Weark** [Imanity-Software/ImanitySpigot3-git#202]
### Expected behavior

It was to be able to put enchanted items in the chests.
I can only place unenchanted items.
I can't unzip a lot of blocks, example: Turn 64 Lapis Lazuli blocks into 9x 64 Lapis Lazuli.

In Minecraft Bedrock Windows 10 I can place an enchanted item by clicking on it and clicking on the chest, but holding Shift and clicking is impossible.

In Minecraft MCPE it is already impossible to place enchanted items in chests.

Watch the video:
https://youtu.be/KJnQXNylVTU

### Observed/Actual behavior

It is not possible to put enchanted items in chests or unpack many items.

### Steps/models to reproduce

Take an enchanted item (I think renamed and lore item also have this problem).
Now open a chest and try to place the item by clicking on it holding the Shift key.

### Plugin list

In Flamecoord I'm using Geyser and Floodgate to add Bedrock Edition support.

### ImanitySpigot3 version

2023.04.1 BUILD 2

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue between TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occurred this issue.

**Comment by Xefreh** [comment]
Hi, can you try do disable this option "dontReadItemNBTDataFromPackets" in imanity/config.yml.

**Comment by Xefreh** [comment]
Issue closed, remember user fixed this in one of my old ticket.
