### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Xayanix** [Imanity-Software/ImanitySpigot3-git#206]
### Expected behavior

-

### Observed/Actual behavior

https://pastebin.com/NrPPtaeM

### Steps/models to reproduce

-

### Plugin list

-

### ImanitySpigot3 version

05.01

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue between TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occurred this issue.

**Comment by Xefreh** [comment]
Issue closed. Incorrect format and no steps on how to reproduce the issue.
