### ISSUE TITLE
ProtocolLib v5.0 still doesn't work even after update

### ISSUE THREAD

**Issue by evolvex3** [Imanity-Software/ImanitySpigot3-git#208]
### Expected behavior

NPC's should have all of their items and armor stands should keep their settings (e.g. invisibility)

### Observed/Actual behavior

https://i.imgur.com/TH2yHOM.png
But there is an improvement comparing to earlier version, because that bug happens less (earlier it was almost on every entity, on screenshot I observed that bug only on 5 entities out of 40)  it happens only when you go far away from entity then go back

### Steps/models to reproduce

Create a NPC or armor stand by plugin

### Plugin list

ProtocolLib v5.0
Citizens

### ImanitySpigot3 version

2023.05.1 LTS BUILD 2 

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue between TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occurred this issue.

**Comment by Xefreh** [comment]
Hi, the issue is from imanity when you enable async entity tracker, please disable it until we found a fix.
