### ISSUE TITLE
Server-side hit detection hitbox

### ISSUE THREAD

**Issue by ItsClairton** [Imanity-Software/ImanitySpigot3-git#209]
### Expected behavior

As in vanilla, hit should work.

### Observed/Actual behavior

If you are too close to the player and you hit him, the hit will not work.

### Steps/models to reproduce

Stay inside the player, but not too much.

Example: https://streamable.com/y7jinh

### Plugin list

All proprietary, the only thing that isn't proprietary is ProtocolLib, FAWE, spark, and LuckPerms.

There is no anticheat in this server.

### ImanitySpigot3 version

2023.05.1 LTS BUILD 2

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue between TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occurred this issue.

### Other

It seems to be something involving the direction the player who hit is looking from.

**Comment by FixYourWork** [comment]
This problem should be only your setup because i just tried this i have got no issue like that.

**Comment by ItsClairton** [comment]
Did you enable server-side hitdetection? What is your current setup?

**Comment by FixYourWork** [comment]
I have tried this with every settings is *enabled*

**Comment by Xefreh** [comment]
Issue Closed. Feature has been removed because of too many issues with it.
