### ISSUE TITLE
CACTUS NO LIMITS

### ISSUE THREAD

**Issue by RoyalMagma** [Imanity-Software/ImanitySpigot3-git#21]
### Expected behavior

CACTUS LIMITS 4 block

### Observed/Actual behavior

![image](https://user-images.githubusercontent.com/87644475/130951681-706e31f6-936a-4f74-9f29-7051ea3b0ab8.png)

### Steps/models to reproduce

cactus

### Plugin list

.

### ImanitySpigot3 version

Build 4 

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

**Comment by LeeGodSRC** [comment]
This issue will be fixed in **2021.09.3 BUILD 6**
