### ISSUE TITLE
TntFiredEvent

### ISSUE THREAD

**Issue by vSKAH** [Imanity-Software/ImanitySpigot3-git#210]
### Votre suggestion est-elle liée à un problème ?

Bonjour, afin d'avoir la main au maximum sur les pillages et sur ce qui touche au TNT j'aimerais avoir un event qui est déclenché quand un TNT passe de l'état de block à l'état d'entité car l'EntitySpawnEvent ne prend pas en compte cette entité.

### Décrivez la solution que vous aimeriez

-  L'event doit prendre en compte et mettre à disposition toutes les raisons qui ont pu mener à l'allumage d'une TNT (avec une enum du style: FLINT_AND_STEEL, DISPENSER, FLAME_BOW ect...) 
- L'event doit mettre à disposition la Location de la TNT au moment ou elle change d'état.
- L'event doit mettre à disposition un Player si la tnt à été allumé directement ou indirectement par un joueur (Directement: Clique droit avec un briquet, Indrectement: Fleche enflamé, Dispenser, Redstone)

Pourquoi pas proposer une version Asynchrone et Synchrone de l'event ?

### Décrivez les alternatives que vous avez considérées

Avec un plugin il faudrait se hook sur beaucoup d'event de bukkit / spigot et donc perdre beaucoup de temps et de "perf" alros que c'est beaucoup plus simple et plus propre de l'intégrer ditrectement dans le spigot

### Accords

- [X] J'ai cherché et vérifié qu'il n'y ai pas d'autre "issue" à propos de ceci.
- [X] J'ai cherché et vérifié que cette fonctionnalité n'est pas déjà présente dans ImanitySpigot3.

**Comment by Whizyyy** [comment]
Bonjour, est-ce qu'un équivalent de [cet event](https://jd.papermc.io/paper/1.14/index.html?com/destroystokyo/paper/event/block/TNTPrimeEvent.html) serait une solution adaptée ? Je ne vois aucun intérêt a proposer "une version asynchrone" de cet event
