### ISSUE TITLE
ViaVersion Incompatibility

### ISSUE THREAD

**Issue by Redwolf223** [Imanity-Software/ImanitySpigot3-git#216]
### Expected behavior

For ViaVersion to work with iSpigot

### Observed/Actual behavior

Since the last update, every time a player join the server or moves the console get spammed from this ViaVersion logs https://pastebin.com/HiHybEbN

### Steps/models to reproduce

Install ViaVersion 4.7.0 with iSpigot 2023.5.1 LTS build 3

### Plugin list

- not needed

### ImanitySpigot3 version

 iSpigot 2023.5.1 LTS build 3

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue between TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occurred this issue.

**Comment by Xefreh** [comment]
Issue closed. too old and was related to Viaversion.
