### ISSUE TITLE
Exception ticking world

### ISSUE THREAD

**Issue by evolvex3** [Imanity-Software/ImanitySpigot3-git#218]
### Stack trace

```
paste your stack trace or a https://paste.imanity.dev/ link here!
```
https://paste.imanity.dev/XvfkGKh

### Plugin list

.

### ImanitySpigot3 version

2023.05.1 LTS BUILD 3

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue between TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occurred this issue.

**Comment by interable** [comment]
first crash log is corelated to [#175 ](https://github.com/Imanity-Software/ImanitySpigot3-git/issues/175)

**Comment by interable** [comment]
make sure that spawnMob is executed synchronously, and it should be fine
I don't think disabling these options will help
some bad plugins, like Vulcan, are causing the first crash

remember that, for example, event.getBlock() in some events also loads chunks

**Comment by FixYourWork** [comment]
I dont agree the last comment.
Im using this with Vulcan no problem at all.
Do not respond ridiculously when someone needs help.
