### ISSUE TITLE
Empty world issue

### ISSUE THREAD

**Issue by FixYourWork** [Imanity-Software/ImanitySpigot3-git#219]
### Expected behavior

I expected to see everything works fine under every conditions.

### Observed/Actual behavior

Problem
If you have empty world(without blocks) and placing blocks will be invisible after 3-5 blocks or be cloned around the blocks you placed like broken FAWE(same for players).
I have tried this all default settings without plugins.
Does not matter what is your configs.

Extra Problem
\imanity\worlds\default.yml

Should unload chunks?
doChunkUnload: true

### Steps/models to reproduce

Fixing it.

### Plugin list

No plugins literally no plugins to be make sure 100%.

### ImanitySpigot3 version

spigotJarVersion: 2023.05.1 LTS BUILD 3
Java: 11

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue between TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occurred this issue.

**Comment by FixYourWork** [comment]
https://github.com/Imanity-Software/ImanitySpigot3-git/assets/130318361/cfd9ad2c-c0d7-4e77-a578-2562932600ca


https://github.com/Imanity-Software/ImanitySpigot3-git/assets/130318361/2d8ba482-32db-4f49-8466-789ba76e499c

**Comment by Xefreh** [comment]
Issue closed. Unable to reproduce on latest version.
