### ISSUE TITLE
Async Explosion Functionality Breaks TNT

### ISSUE THREAD

**Issue by PepziiCola** [Imanity-Software/ImanitySpigot3-git#221]
### Expected behavior

TNT to function the same with async explosions on

### Observed/Actual behavior

TNT does not function the same when Async Explosions is on. When it is off, cannons have the same functionality as other spigots. When Async Explosions is on, cannons don't work at all. Basic boosters don't act the same at all.

### Steps/models to reproduce

https://www.mediafire.com/file/gpqifzoxt85wccy/SimpleCubic.schematic/file

You can use with that schematic and watch the power's boosters not work correctly with async on. I can provide two videos showing the difference via discord. my id is pepzii

### Plugin list

![image](https://github.com/Imanity-Software/ImanitySpigot3-git/assets/118420609/2c7c9004-f6c9-44c7-93f5-3b0bda1efb64)
90% are custom plugins

### ImanitySpigot3 version

spigotJarVersion: 2023.05.1 LTS BUILD 3

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue between TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occurred this issue.

**Comment by LeeGodSRC** [comment]
The mediafire link seems to be expired, can you send me a new one?

**Comment by LeeGodSRC** [comment]
Closing for no further resonse, feel free to open it back
