### ISSUE TITLE
Bug lapis table d'enchantement

### ISSUE THREAD

**Issue by KynnSs** [Imanity-Software/ImanitySpigot3-git#224]
### Comportement attendu

Un problème a été identifié dans la table d'enchantement concernant l'affichage des lapis. Il est nécessaire d'effectuer un double-clic sur un lapis pour afficher les trois lapis, et ce processus doit être répété à chaque utilisation de la table. De plus, un dysfonctionnement survient lorsque plusieurs lapis sont placés dans la table d'enchantement, entraînant leur suppression.

### Comportement actuel/observé

Que la table d'enchantement est bugé 

### Etapes pour reproduire le problème

Utiliser la table d'enchantement

### Liste des plugins

Ce n'est pas dû aux plugins, car j'ai désactivé l'intégralité d'entre eux, et le problème persiste toujours.

### ImanitySpigot3 version

2023.07.1 BUILD 1

### Accords

- [X] J'utilise la dernière version d'ImanitySpigot3 disponible depuis le salon
- [X] J'ai fais des recherches afin d'être certains qu'il n'y est pas déjà une "issue" ouverte à ce sujet.
- [X] J'ai fais des comparaisons du problème entre TacoSpigot 1.8.8 et ImanitySpigot3. Et ce problème se produit seulement avec ImanitySpigot3.

**Comment by Xefreh** [comment]
Issue closed. Unable to reproduce issue with oldEnchanting enabled on latest version.
