### ISSUE TITLE
Issue when preloading a world with the chunk fill processor

### ISSUE THREAD

**Issue by louseee** [Imanity-Software/ImanitySpigot3-git#225]
### Expected behavior

After saving a batch, the server will only generate a single chunk.

### Observed/Actual behavior

After saving a batch, the subsequent chunk loading will be only for a single chunk causing a loss of about ten seconds.
![image](https://github.com/Imanity-Software/ImanitySpigot3-git/assets/77941485/46e2464d-9c19-4f0d-88a8-be36c92eb1d8)

### Steps/models to reproduce

Use this method : `world.imanity().newChunkFillProcessor(location, 1000).log(true)).start();`

### Plugin list

None

### ImanitySpigot3 version

 2023.07.1 BUILD 1

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue between TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occurred this issue.

**Comment by LeeGodSRC** [comment]
There can be various reasons where chunks are generated slower than expected, chunk generation is very depends on the surrounding chunks to generate, if a chunk needs 10 surrounding chunks to generate, it will wait until those 10 chunks to be in the same state before the chunk can be generated.
Which means during those times it possibly trying to bring a lot of chunks into a state but it doesn't count as generated.

**Comment by Xefreh** [comment]
Issue Closed. @LeeGodSRC explained why it might be slow. We may implement a feature to allow x threads to be used for chunk generation tasks such as using the fillWorld command and though the API.
