### ISSUE TITLE
Invisible player with UUID spoof

### ISSUE THREAD

**Issue by CyriacF** [Imanity-Software/ImanitySpigot3-git#226]
### Expected behavior

A working /nick system with a new skin and nickname

### Observed/Actual behavior

The player entity is invisible to other players, but visible in the tablist.

### Steps/models to reproduce

![image](https://github.com/Imanity-Software/ImanitySpigot3-git/assets/49961233/4caa3716-db66-4b7f-a7d4-8b12a299dbcd)
![image](https://github.com/Imanity-Software/ImanitySpigot3-git/assets/49961233/cdc79955-5941-4682-9018-8a360738eccc)

### Plugin list

ProtocolLib v5.1
Custom nick system

### ImanitySpigot3 version

2023.07.1b1

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue between TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occurred this issue.

### Other

Work fine on 2023.02.1 LTS Build 6 but not when i upated to 2023.07.1b1 (maybe commit between this two version)

**Comment by SiriHackYT** [comment]
Work on commit : Added ghostBucketFix option
But doesnt work in commit : Flush packet before fall triggers

When i remove all change "Flush packet before fall triggers" in commit Added bucketUpdateRange option, it doesn't work too

**Comment by SiriHackYT** [comment]
After try fixed when i disable the new anti xray all works

**Comment by Xefreh** [comment]
Issue sounds to be fixed. Closing this issue.
