### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by KikyoC** [Imanity-Software/ImanitySpigot3-git#227]
### Comportement attendu

Je suis sensé pouvoir ouvrir ma clé de cosmétique. Dans une utilisation normale, je suis sensé pouvoir voir des coffres qui apparaissent  

### Comportement actuel/observé

https://www.youtube.com/watch?v=t7cwBLciIp8

### Etapes pour reproduire le problème

Lancer le serveur avec la version 2023.05.1 LTS BUILD 3,
Installer le plugin UltraCosmetics: https://www.spigotmc.org/resources/1-8-8-1-20-1-ultra-cosmetics-opensource-free.10905/

### Liste des plugins

Plugins (21): WorldEdit (6.1.9;caf0ad9), PlaceholderAPI (2.11.3), AdvancedCrates (3.9.16), SwordLobby (1.0-SNAPSHOT), ViaVersion (4.7.0), MyPluginsCore (1.0), HolographicDisplays (3.0.0), ProtocolLib (5.1.0-SNAPSHOT-661), WorldGuard (6.1), Multiverse-Core (2.5-b699), LuckPerms (5.4.98), BungeeGuard (1.4.1), TAB (4.0.3), LPX (3.3.1), Vault (1.7.3-b131), TigerReports (5.2.1), UltraCosmetics (3.3), VaultChatFormatter (1.1-SNAPSHOT), Economy (2.3), CommandPanels (3.19.1.2), spark (1.10.53)

### ImanitySpigot3 version

2023.05.1 LTS BUILD 3

### Accords

- [X] J'utilise la dernière version d'ImanitySpigot3 disponible depuis le salon
- [X] J'ai fais des recherches afin d'être certains qu'il n'y est pas déjà une "issue" ouverte à ce sujet.
- [X] J'ai fais des comparaisons du problème entre TacoSpigot 1.8.8 et ImanitySpigot3. Et ce problème se produit seulement avec ImanitySpigot3.

### Other

Merci d'avance pour votre aide

**Comment by datatags** [comment]
For reference, this method was added to Bukkit in commit [01d1820](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/01d1820664a5f881665b84b28871dadd132deaef)

**Comment by LeeGodSRC** [comment]
The method was added in newer version of spigots, I will consider this as a feature request
