### ISSUE TITLE
CRASH WITHOUT ANY ERROR MASSAGE NEED ASAP MORE THAN 200 PLAYERS WAITING

### ISSUE THREAD

**Issue by SkyGaut** [Imanity-Software/ImanitySpigot3-git#228]
### Message d'erreur en console

```
Collez votre erreur ou votre lien https://paste.imanity.dev/ ici!
```

https://paste.imanity.dev/mqlQYYZ

### Liste des plugins

![image](https://github.com/Imanity-Software/ImanitySpigot3-git/assets/77456864/fa0a2e1d-ed38-4597-aa69-eea8d4addc75)

### Etapes pour reproduire le problème (si vous le savez)

Ramener environs 150/200 joueurs sur le serveur et au bout de quelques heure le serveur crash alors que le serveur n'utilise que 40 /100 des performance de la machine

### ImanitySpigot3 version

[19:44:55 INFO]: [Rancha] ImanitySpigot is currently running under version 2023.02.1 LTS BUILD 6
[19:44:55 INFO]: [Rancha] Rancha is currently running under version 2023.02.1 BUILD 3

### Accords

- [X] J'utilise la dernière version d'ImanitySpigot3 disponible depuis le salon
- [X] J'ai fais des recherches afin d'être certains qu'il n'y est pas déjà une "issue" ouverte à ce sujet.
- [X] J'ai fais des comparaisons du problème entre TacoSpigot 1.8.8 et ImanitySpigot3. Et ce problème se produit seulement avec ImanitySpigot3.

### Autre

J'ai besoin d'aide au plus rapidement car j'ai plus de 250 joueurs qui attendent le serveur ouvert pour jouer dessus

**Comment by LeeGodSRC** [comment]
Try to update your ImanitySpigot3 to latest version and try again

**Comment by SkyGaut** [comment]
i did, and it still does the error. The server crash when people enter in corrupted chunk. Do you know how to fix that ?

**Comment by LeeGodSRC** [comment]
> i did, and it still does the error. The server crash when people enter in corrupted chunk. Do you know how to fix that ?

Try to get the corrupted chunk removed

**Comment by Xefreh** [comment]
If you have a corrupted chunk, make this chunk not loadable from the server though a plugin. I think Protocollib 5.0 is having a few issues with imanityspigot at the moment and karhu always had issues anyway. If you need a good anticheat you can purchase vulcan but if you are looking for better detections take a look at polar.

**Comment by Xefreh** [comment]
Issue closed, impossible to determine performances issues and also using leaking plugins from a known server that have performance issues.
