### ISSUE TITLE
Blockhit and Consumable Bug

### ISSUE THREAD

**Issue by Tentoxa** [Imanity-Software/ImanitySpigot3-git#229]
### Is your feature request related to a problem?

Yes.
When blocking your sword and opening a GUI at the same time the sword wont unblock (Also for consumables and bows).
This is an issue on spigot. 

I have players on my server who are abusing the bug and I thought maybe you could add a fix to that. Since its not related to imanity its not a problem i guess

### Describe the solution you'd like.

The Players Sword should get unblocked. Or if he abuses the bug with a consumable or a bow it should also be stopped.

### Describe alternatives you've considered.

There are no Plugins for fixing this issue

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest ImanitySpigot3.

### Other

Video of the Bug: https://youtu.be/2qyymjMG-WM

**Comment by Zetthh** [comment]
I have the same problem, any solution?

**Comment by Tentoxa** [comment]
> I have the same problem, any solution?

didnt find any

**Comment by Xefreh** [comment]
in the next update you'll be able to disable processPacketswhileSleeping, our modern tick loop is actually causing a rare bug where players can eat twice.
