### ISSUE TITLE
Rod velocity doesn't exist on iSpigot 3.

### ISSUE THREAD

**Issue by LeSGYT** [Imanity-Software/ImanitySpigot3-git#23]
### Is your feature request related to a problem?

Because my players are used for a specific rod velocity, and the normal one isn't good.

### Describe the solution you'd like.

Add 
Such values like,

"rod_hori": 0.8,
"rod_vert": 0.8,
"bow_hori": 0.8,
"bow_vert": 0.8,

which were on ispigot2

### Describe alternatives you've considered.

I can do it using another spigot, but I very like ispigot3 since it can load my worlds much faster than any other spigot.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest ImanitySpigot3.

**Comment by LeeGodSRC** [comment]
New implementation has been applied to 2021.09.2b1 to made Rod velocity possible
