### ISSUE TITLE
Aucun mob ne spawn

### ISSUE THREAD

**Issue by MathisBruel** [Imanity-Software/ImanitySpigot3-git#230]
### Comportement attendu

Des mobs hostile spawn sur la map

### Comportement actuel/observé

Aucune mob hostile ne spawn sauf lors d'un restart du serveur il y a 3 à 5 mobs qui spawn à coté du joueur et sa s'arrête là

### Etapes pour reproduire le problème

- après avoir vérifier le /gamerule doMobSpawning true et le /difficulity 2 bien évidement

### Liste des plugins

aucun (serveur vierge)

### ImanitySpigot3 version

2023.10.1 LTS BUILD 2

### Accords

- [x] J'utilise la dernière version d'ImanitySpigot3 disponible depuis le salon
- [X] J'ai fais des recherches afin d'être certains qu'il n'y est pas déjà une "issue" ouverte à ce sujet.
- [X] J'ai fais des comparaisons du problème entre TacoSpigot 1.8.8 et ImanitySpigot3. Et ce problème se produit seulement avec ImanitySpigot3.

**Comment by Xefreh** [comment]
par défaut le spawn des mobs est assez long, je te conseille de modifier les options dans bukkit.yml à la section "spawn-limits".
moi j'ai mis les monstres à 10000 et ça spawn énormément donc joue un peu ces valeurs.

exemple:
```
spawn-limits:
  monsters: 10000
  animals: 15
  water-animals: 5
  ambient: 15
```

**Comment by Xefreh** [comment]
Selon moi tu as un problème de configuration c'est tous car je n'ai pas ce problème.

**Comment by MathisBruel** [comment]
Bah c'est sur un serveur vierge donc je vois pas le problème de configuration... Avec un autre truc que Imanity sa fonctionne mais dès que je fait avec, bah rien, le néant mdr

**Comment by Xefreh** [comment]
@MathisBruel could you provide us enough proof that mobs are not spawning please or else I'm going to have to close this issue. we are aware of mobs not spawning in end btw.

**Comment by Xefreh** [comment]
Issue closed. I cannot reproduce the issue (configuration issue)
