### ISSUE TITLE
block hit damage management

### ISSUE THREAD

**Issue by DragonL0508** [Imanity-Software/ImanitySpigot3-git#233]
### Is your feature request related to a problem?

Many players in HCF now abuses blockhit (because autoclicks have became legit) and the only real way to keep the game playable is to reduce the damage resistance

### Describe the solution you'd like.

an option to manage sword blocking damage resistance

### Describe alternatives you've considered.

I cant seem to find a plugin to do that

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest ImanitySpigot3.

**Comment by Xefreh** [comment]
Issue closed. Paper already has this feature called "player-blocking-damage-multiplier" in paper.yml.
