### ISSUE TITLE
Invisible Players with Bolt Practice

### ISSUE THREAD

**Issue by serumanooo** [Imanity-Software/ImanitySpigot3-git#237]
### Expected behavior

I expect the player to be visible, since it never happened before I switched to ImanitySpigot.

### Observed/Actual behavior

It looks like chunks take 1-2 seconds to load and then you cant see your opponent.

### Steps/models to reproduce

There is no specific way to reproduce it, its just random.

### Plugin list

- FastAsyncWorldEdit (21.03.26-5ff3a9b-1286-22.3.9), 
- PlaceholderAPI (2.11.6), 
- Wave (1.0), (Our Core)
- ViaVersion (4.9.3), 
- Vault (1.7.3-b131), 
- ProtocolLib (5.1.0), 
- ViaRewind (3.0.6), WorldEdit (6.1.9;caf0ad9), 
- DecentHolograms (2.8.8), 
- Retention (2.4), 
- BungeeGuard (1.4.4), 
- Duels (1.0), LPX (3.4.7), 
- WaveGuard (1.14), (Our Anticheat)
- EasyCommandBlocker (1.9.1), 
- WorldGuard (6.1.3-SNAPSHOT;c904242), 
- Phoenix (1.6.12-30b8ab0), 
- Bolt (1.2), 
- pxStaff (87b5d68), 
- pxFriends (0bf6abc), 
- pxBasic (f38a79b), 
- spark (1.10.73)

### ImanitySpigot3 version

2024.06.1 BUILD 5

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue between TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occurred this issue.

### Other

Here is a video showing the bug: https://youtu.be/P6hDzTkilsY
It doesnt happen all the time, and I dont believe its exactly a chunk issue, cuz the chunks load just fine for the other player, it never happens for both players at the same time.
I also tried changing Imanity settings, and no matter what I change on it, I cant fix the bug.
I tested with other spigot and it didnt happen.

**Comment by Xefreh** [comment]
Have you ever tried to disable async chunk generation/loading or disable async entity tracker ?

**Comment by serumanooo** [comment]
> Have you ever tried to disable async chunk generation/loading or disable async entity tracker ?

Yeah, as I said in the post, I tried changing a lot of config options, none of them fixed the issue

**Comment by serumanooo** [comment]
Idk if this other bug is related to the one in the post, but this also happens when the server is using ImanitySpigot:
https://youtu.be/CCSJ0GUMlwY
This used to happen with CarbonSpigot and was fixed some months ago.
It was related to async entity tracker or something like that

**Comment by Fluid4321** [comment]
Same issue.

**Comment by Xefreh** [comment]
Hi, so I tested using a small code to try if vanishing players had an issue on ispigot but I've not found any.
my code:
```java
package fr.xefreh.testvanish;

import org.bukkit.Bukkit;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.bukkit.plugin.java.JavaPlugin;

import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

public class Main extends JavaPlugin implements CommandExecutor {
	public static final Map<UUID, UUID> hidingMap = new HashMap<>();

	@Override
	public void onEnable() {
		this.getCommand("vanish").setExecutor(this);
	}

	@Override
	public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
		if (sender instanceof Player) {
			Player player = (Player) sender;
			Player target = Bukkit.getPlayer(args[0]);
			if (target != null && target != player) {
				if (hidingMap.get(player.getUniqueId()) == target.getUniqueId()) {
					hidingMap.remove(player.getUniqueId());
					sender.sendMessage("showing player " + target.getName());
					player.showPlayer(target);
				} else {
					hidingMap.put(player.getUniqueId(), target.getUniqueId());
					sender.sendMessage("hiding player " + target.getName());
					player.hidePlayer(target);
				}
			} else {
				sender.sendMessage("Player not found");
			}
			return true;
		}
		return false;
	}
}
```

**Comment by Xefreh** [comment]
maybe bolt assumes that if a player is dead, it doesn't need to showPlayer again.

**Comment by LeeGodSRC** [comment]
Not ImanitySpigot3 issue, confirmed by Bolt developer.
![](https://cdn.discordapp.com/attachments/902775452521873420/1259769451470131262/image.png?ex=668ce33a&is=668b91ba&hm=d2f76a3918a28e610f30d1046b0e93efff01090a5720b8fa7cd05682a767656d&)
