### ISSUE TITLE
Invisible Players on Imanity Spigot

### ISSUE THREAD

**Issue by Fluid4321** [Imanity-Software/ImanitySpigot3-git#239]
### Expected behavior

You should be able to see you apponent. 

### Observed/Actual behavior

My apponent is occasionally invisible.

### Steps/models to reproduce

It seems to be happening randomly for me.

### Plugin list

Apollo-Bukkit 1.1.3, FAWE 18.10.25, Via Version 4.10.2, Vault, VIaBackwards 4.10.2 PlaceholderAPI 2.11.3 ProtcolLib 5.0.0, Via Rewind 3.1.2, Core, Citizens 2.0.29, World edit, Practice (BOLT), Spark

### ImanitySpigot3 version

2024.06.1 BUILD 5

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue between TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occurred this issue.

**Comment by Fluid4321** [comment]
Tried with Async Entity Tracker off.

**Comment by LeeGodSRC** [comment]
Duplicated Issue of https://github.com/Imanity-Software/ImanitySpigot3-git/issues/237
