### ISSUE TITLE
Make Imanity's knockback more consistent

### ISSUE THREAD

**Issue by serumanooo** [Imanity-Software/ImanitySpigot3-git#240]
### Is your feature request related to a problem?

Today I was trying to do a Knockback profile in ImanitySpigot so I could change from CarbonSpigot, because there's some features in Imanity that I like better. But, when I queued a boxing match against one of my server's Admins, we noticed that we couldnt keep a combo on eachother.
This is what happens: At the second/third hit, the opponent takes almost no knockback (mid-air).

Then we noticed it happens when we are in the air and hold W, for some reason, when you do it, your knockback is almost null.
Here is a short clip showing what happens:
https://youtu.be/JaDeM1A9HE8
But it was weird, because I have two KB Profiles, one for speed kits and one for regular kits, and they are almost the same, the only difference is that horizontal knockback is slightly higher at the speed one. And when we tested the other profile, this wouldnt happen, so I believe KB is messed up when you have speed effect.

Just to put it side-to-side, this is what my KB profile looks like in CarbonSpigot:
https://youtu.be/EzXSXNDWdd8
I cant replicate it in ImanitySpigot no matter how much I tried. (I tried changing lots of values to see if it would resolve my issue, didnt get any results, Xefreh also tried helping me but we concluded that it is really a Imanity bug)

Extra: We also noticed that you can easily win hit trades by just holding W against your opponent, you dont even have to click fast, a friend could beat me with 1 cps. Its not SUPER OP, but its still weird that you dont even have to try to not take knockback, you shouldnt be able to go against someone that is W-Tapping + doing 16 CPS while youre holding W and doing 1 CPS.
But, maybe this part is because in order to achieve the knockback showed in the second video, we dont use ExtraHorizontal or ExtraVertical knockback. 
(This doesnt affect the first issue, we tried with a normal KB profile too and the bug was still there. We didnt test this second issue with a normal KB profile though.)
[Normal = KB Profile that uses at least ExtraHorizontal knockback, in other words, a KB profile that doesnt have it set to 0.0]

### Describe the solution you'd like.

Make Imanity's knockback more consistent and please fix this thing about holding W being super OP.
With CarbonSpigot I have a similar issue where CPS is super OP (because of static KB), we can deal with it, but holding W being something OP completely breaks PvP.
[Static KB = KB Profile with ExtraHorizontal set to 0.0]

### Describe alternatives you've considered.

No alternatives.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest ImanitySpigot3.

### Other

Video showing the issue: https://youtu.be/JaDeM1A9HE8

**Comment by Xefreh** [comment]
Issue closed. it was related to friction.
