### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by serumanooo** [Imanity-Software/ImanitySpigot3-git#244]
### Stack trace

Console error:
https://paste.imanity.dev/19usPgwP5wm7OjX

Crash report:
https://paste.imanity.dev/3zrcoEmdYL2iohd

### Plugin list

Plugins (23): FastAsyncWorldEdit (888d0e9e), PlaceholderAPI (2.11.6), Wave (1.0), ViaVersion (4.10.2), Vault (1.7.3-b131), ViaBackwards (4.10.2), ProtocolLib (5.1.0), ViaRewind (3.1.2), WorldEdit (6.1.8-SNAPSHOT;cd4729f), DecentHolograms (2.8.9), BungeeGuard (1.4.4), Retention (2.5), Duels (1.0), LPX (3.4.7), WaveGuard (1.14), EasyCommandBlocker (1.9.1), WorldGuard (6.1.3-SNAPSHOT;c904242), Phoenix (1.7.5-8afbac1), Bolt (1.2), pxStaff (f4e391a), pxFriends (0bf6abc), pxBasic (8c9ad49), spark (1.10.92)

### Steps/models to reproduce (if known)

Idk

### ImanitySpigot3 version

2024.06.1 BUILD 5

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue between TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occurred this issue.

**Comment by LeeGodSRC** [comment]
Have you tried enabling compatibilityMode?

**Comment by Xefreh** [comment]
> Have you tried enabling compatibilityMode?

yes it fixed his issue. I'am closing this issue.
