### ISSUE TITLE
Enchantment Display Issue on Item Shift or Drag Out

### ISSUE THREAD

**Issue by lulu2002** [Imanity-Software/ImanitySpigot3-git#253]
### Expected behavior

The enchantment should be displayed on the item when it’s shifted out or instantly dragged out.

### Observed/Actual behavior

When I shift-click or drag the item out quickly, the enchantment is not showing up on the item as expected.

### Steps/models to reproduce

1. Apply enchantment to an item.
2. Shift-click or drag the item out of its inventory slot. (faster than the enchant glow shows)
3. Observe that the enchantment is not displayed on the item.
4. After close the inv, the enchant shows

### Plugin list

It's bugged on empty server

### ImanitySpigot3 version

2024.09.1 LTS BUILD 4

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue between TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occurred this issue.

### Other

PaperSpigot doesn't have this problem (verified)

**Comment by lulu2002** [comment]
https://imgur.com/a/Bp6vIgW

**Comment by LeeGodSRC** [comment]
This issue will be resolved in the next version.

**Comment by LeeGodSRC** [comment]
Fixed in `2024.10.1 BUILD 3`
