### ISSUE TITLE
Mobs Spawning Despite doMobSpawning Gamerule Set to false

### ISSUE THREAD

**Issue by lulu2002** [Imanity-Software/ImanitySpigot3-git#255]
### Expected behavior

When `gamerule doMobSpawning false` is set, no mobs should spawn in newly loaded chunks or anywhere in the world.

### Observed/Actual behavior

Despite setting `gamerule doMobSpawning false`, mobs still spawn when new chunks are loaded. The issue can be reproduced even in a fresh world.

### Steps/models to reproduce

1. Create a new world.
2. Set `gamerule doMobSpawning false`.
3. Use the `/kill @e` command to remove all existing mobs.
4. Travel to a new area to load fresh chunks.
5. Observe that mobs are still spawning despite the gamerule setting.

### Plugin list

Without any plugins

### ImanitySpigot3 version

2024.09.1 LTS BUILD 4

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I have compared the issue between TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occurred this issue.

### Other

This is proven and should be able  to reproduce without setting up any env, here's the world file if needed (since it shouldn't be needed, happens on every world)
[world.zip](https://github.com/user-attachments/files/17647273/world.zip)

**Comment by LeeGodSRC** [comment]
The issue presents in PaperSpigot 1.8.8, and it's a different issue from the client that reported the issue.

**Comment by xN0MANDx** [comment]
In PaperSpigot it's working fine (0 entities), in imanity don't (15 000++ entities).
That's how it look in imanity (it's ignoring gamerule doMobSpawning and starts spawning thousands of animals):
[https://www.youtube.com/watch?v=iRhULXLh8YA](video 1)
[https://www.youtube.com/watch?v=EDp5bZTEON0](video 2)
