### ISSUE TITLE
Critical Performance Issue

### ISSUE THREAD

**Issue by Xefreh** [Imanity-Software/ImanitySpigot3-git#257]
### Expected behavior

the server should not start to lag.

### Observed/Actual behavior

PlayerChunkMap$PlayerChunk.tickChunkMap() is taking too much time making main thread slow and reducing tps at 100+ players.

### Steps/models to reproduce

stress test a server.

### Plugin list

https://spark.lucko.me/OEVHLJkS0C?hl=32000,33847

### ImanitySpigot3 version

2024.10.1 

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue between TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occurred this issue.

**Comment by Xefreh** [comment]
the tests were run on a dedicated server at hetzner i9 12900K

**Comment by LeeGodSRC** [comment]
Should be fixed by `2024.10.1 BUILD 4`
