### ISSUE TITLE
[建議和想法] 完善Premium自定義信息功能, 當機尖峰記錄器想法

### ISSUE THREAD

**Issue by HappyAreaBean** [Imanity-Software/ImanitySpigot3-git#27]
### Is your feature request related to a problem? 你的問題是否與一個問題有關?

因為沒有人出來問這些事情所以我是第一個 xd
在ImanitySpigot 3中，有部分信息不能完全自定義。
正因為如此，它不能真正被列為 "完全自定義信息"。
對於這個問題，有一些建議和想法。
還包括了一些與標題提到的相關內容

## 警告顏色
目前在 `tpsCommand` 中**已知被鎖定**的變量是 `<tps5s>, <tps10s>, <tps1m>, <tps5m>,
  <tps15m>, <fullServerTick>, <worldTick>, <entities>, <loadedChunks>`
因為它們似乎都具有相同的警告顏色，因此可以通過添加編輯警告顏色的選項來完成。
例如 `高 = 紅色`, `中 = 黃色`, `低 = 綠色`

## 啟用和禁用 (Enable and Disable)
在 `mobAIMessage` 中有一個名為 `<state>` 的變量, 輸出 `enable` 和 `disable` 信息
這也可以通過添加更改信息的選項來完成
直至目前為止，目前只有一則訊息使用啟用和禁用，如果添加更改啟用和禁用信息的選項，未來如果要加入其他信息也不會太困難。

## 信息
1. 在使用指令 `/plugins (/pl)` 查看插件列表時，在顯示最後一個插件的時候不應該顯示逗號
2. 某些指令的信息對比其他的指令有很大的分別，例如 使用方法, 成功/錯誤訊息

---

## 當機尖峰記錄器 (Lag Spike Logger)
當然的這個功能對任何人來說，都是一個很方便的功能可以更容易檢查到底是什麼原因造成卡頓
但是我認為仍然有些方法可以讓這個功能更有實用性或便利性

目前記錄都是在檔案或是遊戲中用滑鼠移動到懸停文本(Hover Text)可以看到
當我第一次嘗試這個功能時，我認為這是一個方便的功能，可以找出導致當機/問題的原因。
但是在某些情況下，我覺得使用檔案記錄，有一點點降低這個可用性。
例如說設定中有一個選項。防止記錄到大量當機記錄的時候。會一直寫入重複的檔案。
但是在某些情況下這些大量記錄中可能會寫入一些重要的信息
並且如果你要去找相對應時間的記錄檔案會變得很困難，況且大量檔案處理起來也是蠻麻煩的。
我相信部分人應該會直接把它關掉。（像我這樣）

因為 imanity 現在擁有自己的 pastebin 伺服器，我認為這是一個不錯的主意可以把記錄融入到pastebin。
對於用戶來說與其使用[純文字版本](https://paste.imanity.dev)，使用[有介面的版本](https://code.imanity.dev)更具可讀性和可用性。

---

## 一些範例
上面的信息的部分也許可以把選項弄成這樣:
```yaml
misc:
  state:
    enable: '&aenable'
    disable: '&cdisable'
  warning:
    high: '&c'
    medium: '&e'
    low: '&a'
```
當機尖峰記錄器也許可以弄成這樣:
![img](https://i.imgur.com/0zdTlxH.png)
那當然的 [INFO] [UPLOAD] 這些文字應該都要可以編輯才對
也可以讓用戶自訂時間格式怎麼顯示

### Describe alternatives you've considered. 你是否有想過其他的解決方法?

N/A

### Agreements 同意事項

- [X] 我已經嘗試在 Issues 中搜尋是否有人提出類似的建議
- [X] 我已經確定這個功能並沒有實裝到最新版的 ImanitySpigot3 中

### Others 額外資訊

我花了大約 3 個小時(或者更多)來決定我需要寫什麼，思考什麼是最好的例子，找到一些想法。
 @如果我說我不在乎是否會添加或使用任何想法或建議，老實說這肯定是假的，我怎麼不可能不在乎xd，但是心裡還是有底啦w

That's all. Thank you :)
Maybe I'll edit or post a new reply for update.

**Comment by Whizyyy** [comment]
Option available since a long time now
