### ISSUE TITLE
Stack trace

### ISSUE THREAD

**Issue by xpghard** [Imanity-Software/ImanitySpigot3-git#28]
### Stack trace

![257559d28917cca0d365aa069548cc8a](https://user-images.githubusercontent.com/46456820/131525420-d02640e7-3466-4680-be93-f171f83adcef.png)

### Plugin list

zero plugins

### Steps/models to reproduce (if known)

i download 
![71ff26408a14daf674aa94fe61164a35-png](https://user-images.githubusercontent.com/46456820/131525751-c4e243ec-5840-447f-880c-be08756dca55.jpg)
and run this and i have error

### ImanitySpigot3 version

spigotJarVersion: 2021.08.1 BUILD 8

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

**Comment by LeeGodSRC** [comment]
This issue will be fixed in **2021.09.1 BUILD 1**
