### ISSUE TITLE
Collections.singletonList error

### ISSUE THREAD

**Issue by XBeTeRR** [Imanity-Software/ImanitySpigot3-git#29]
### Expected behavior

https://pastebin.com/iQD6DJBf Java 8

### Observed/Actual behavior

https://pastebin.com/iQD6DJBf Java 8

### Steps/models to reproduce

https://pastebin.com/iQD6DJBf Java 8

### Plugin list

Fairy, ImanityFramework , ProtocoLib

### ImanitySpigot3 version

spigotJarVersion: 2021.08.1 BUILD 8

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

### Other

https://pastebin.com/iQD6DJBf Java 8

**Comment by LeeGodSRC** [comment]
First, why do you have both Fairy and ImanityFramework at the same time?
Second, please send us a full log

**Comment by LeeGodSRC** [comment]
No Further Information & It looks more like an issue from plugins so I will close it for now
