### ISSUE TITLE
[問題回報] 1.9+ 即時重生

### ISSUE THREAD

**Issue by HappyAreaBean** [Imanity-Software/ImanitySpigot3-git#3]
**預期狀況**
死亡時移除玩家的紅屏和死亡動畫

**實際狀況**
紅屏

**重現的方式**
1. 把一個玩家砍死
2. 紅屏存在

**插件列表**
`PlugMan (2.1.7), ViaRewind (2.0.0), ViaVersion (4.0.0)`

**ImanitySpigot3 版本**
2021.06.1 BUILD 5

**你回報問題的當下符合以下的所有事項.  (如果符合的話, 在 [ ] 中填一個 x)**
- [x] 我目前運行的 ImanitySpigot3 版本在 #client-info 頻道中有顯示在 正在支援 的版本列表裡.
- [x] 我有在這個 Issue Tracker 中搜尋過並沒有發現類似的問題回報.
- [x] 我已經把原版的 TacoSpigot 1.8.8 和 ImanitySpigot3 互相比較過並且確定只有 ImanitySpigot3 會發生這個問題.

**額外資訊**
有把這個開起來
```yaml
# This option will remove the red screen & death animation when a player died
# Completely remove the delay when died.
instantRespawn: true
```

**Comment by LeeGodSRC** [comment]
Via-Version在 1.9+ 中新增了功能 "use-new-deathmessages"
主要是在偵測到玩家死亡時會在傳送一個 Death Screen 給玩家

所以在 **2021.06.1 BUILD 6** 中將會新增註解要求關閉該選項
