### ISSUE TITLE
Cannot create normal world

### ISSUE THREAD

**Issue by DerStandard** [Imanity-Software/ImanitySpigot3-git#33]
### Stack trace

https://paste.imanity.dev/B2681a6

### Plugin list

Own plugins without world changes

### Steps/models to reproduce (if known)

Start a new server with optimized config and java 16

### ImanitySpigot3 version

2021.09.2 BUILD 2

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

### Other

Im using Java 16

**Comment by LeeGodSRC** [comment]
Hello, We've tested ourself with OpenJDK 16 and the issue doesn't seems to occur
Can you provide us your rancha.yml & imanity.yml and a full log?
And test without plugins yourself? note that a bunch of plugins made for 1.8 may have some incompatibility issue. So it's better to try

**Comment by DerStandard** [comment]
Yes I resolved it. The problem was the "Cloud-System". It's using another google guava version and starts the spigot with his own class loader.
Without all plugins and the cloudsystem i'ts running normally.

Optionally the link:
https://www.spigotmc.org/resources/simplecloud-simplify-your-network.79466/
