### ISSUE TITLE
[問題回報] 1.16進入伺服器會卡在載入地形中

### ISSUE THREAD

**Issue by HappyAreaBean** [Imanity-Software/ImanitySpigot3-git#4]
**預期狀況**
進入伺服器

**實際狀況**
卡在載入地形中

**重現的方式**
1. 進入伺服器
2. 卡在載入地形中

**插件列表**
`PlugMan (2.1.7), ViaRewind (2.0.0), ViaVersion (4.0.0)`

**ImanitySpigot3 版本**
2021.06.1 BUILD 5

**你回報問題的當下符合以下的所有事項.  (如果符合的話, 在 [ ] 中填一個 x)**
- [x] 我目前運行的 ImanitySpigot3 版本在 #client-info 頻道中有顯示在 正在支援 的版本列表裡.
- [x] 我有在這個 Issue Tracker 中搜尋過並沒有發現類似的問題回報.
- [x] 我已經把原版的 TacoSpigot 1.8.8 和 ImanitySpigot3 互相比較過並且確定只有 ImanitySpigot3 會發生這個問題.

**額外資訊**
Async Chunk 是關的
如果那個玩家死亡了的話重生後會變正常 (/kill 或者是死亡都可以)
已經測試過1.9也有同樣的問題，所以推測應該1.8以上的版本都會有同樣的問題

**Comment by LeeGodSRC** [comment]
該問題將在 **2021.06.1 BUILD 6** 中被解決
