### ISSUE TITLE
Rod speed, Bow speed and Disabling op/deop

### ISSUE THREAD

**Issue by Boryte** [Imanity-Software/ImanitySpigot3-git#43]
### Is your feature request related to a problem?

No, it's not related to a problem.

### Describe the solution you'd like.

It'd be amazing to have more options in the spigot or knockback system.
Fishing Rod speed which can be seen (https://www.mc-market.org/resources/14434/)
Bow arrow speed (never seen before, but would work the same like fishing rod speed)
And option in the spigot to disable op/deop feature completely. It's not needed and can be abused by external plugin. It'd be amazing to have that option inside spigot in case we need it or not.

### Describe alternatives you've considered.

Plugins which causes unnecessary load on the server.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest ImanitySpigot3.

**Comment by LeeGodSRC** [comment]
Rod speed / bow speed modification can now be achieved from projectile behaviour in **2021.10.1 BUILD 13**
