### ISSUE TITLE
Netty can't be patched with Java 17

### ISSUE THREAD

**Issue by HappyAreaBean** [Imanity-Software/ImanitySpigot3-git#45]
### Expected behavior

Netty should be patched with Java 17

### Observed/Actual behavior

Unable to patch Netty with Java 17
```
[18:17:00 INFO]: Patching Netty, please wait.
[18:17:00 ERROR]: Could not patch Netty! You are probably using Java Version above Java 12! Please add this startup flag --illegal-access=permit to fix it!
```

### Steps/models to reproduce

Use Java 17 to start the server

### Plugin list

N/A

### ImanitySpigot3 version

2021.10.1 BUILD 6

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

### Other

```
OpenJDK 64-Bit Server VM warning: Ignoring option --illegal-access=permit; support was removed in 17.0
```

**Comment by LeeGodSRC** [comment]
The bug has been fixed in **Rancha 2021.11.1 LTS BUILD 1**
