### ISSUE TITLE
Anti Xray 

### ISSUE THREAD

**Issue by Cryptics1999** [Imanity-Software/ImanitySpigot3-git#48]
### Is your feature request related to a problem?

Antixray in spigot is kind of bad when u put it on engine 2

### Describe the solution you'd like.

Anti xray isnt inbuilt in paper in 1.8 I wondered if you guys coud make something similar to what paper made with antixray

### Describe alternatives you've considered.

Not sure

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest ImanitySpigot3.

**Comment by xpghard** [comment]
As far as I can see in a good configuration it rather works fine apart from the server load. It's rather better for x-ray to be on async but it rather depends on whether leegod accepts it.

**Comment by xpghard** [comment]
I found an example code. https://github.com/stonar96/RayTraceAntiXray
