### ISSUE TITLE
Do AsyncTabCompleteEvent for player.

### ISSUE THREAD

**Issue by TheMatrozo** [Imanity-Software/ImanitySpigot3-git#55]
### Is your feature request related to a problem?

In 50%. It's about AsyncTabCompleteEvent. 

### Describe the solution you'd like.

I think about do AsyncTabCompleteEvent work also to player.

### Describe alternatives you've considered.

It's possible by using ProtocolLib by packet TAB_COMPLETE, but this can only send message normal message with command list and override player typed command. 

### Agreements

- [x] I have searched for and ensured there isn't already an open issue regarding this.
- [x] I have ensured the feature I'm requesting isn't already in the latest ImanitySpigot3.

**Comment by LeeGodSRC** [comment]
The feature has been added in **ImanitySpigot3 2021.11.1 LTS BUILD 1**
