### ISSUE TITLE
Ability to disable ImanitySpigot3 built-in commands

### ISSUE THREAD

**Issue by ProPractice** [Imanity-Software/ImanitySpigot3-git#56]
### Is your feature request related to a problem?

Not really, it's a quality of life feature.

### Describe the solution you'd like.

I'd like an option to disable commands such as **/ping** as I would like it to be formatted differently using a plugin. Currently the commands inside of the Spigot don't seem to be able to be overwritten.

### Describe alternatives you've considered.

I have tried to implement a /ping command to overwrite the existing one but the Spigot command takes priority.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest ImanitySpigot3.

**Comment by xpghard** [comment]
@ProPractice 
You can do this by unregistering all ispigot commands using the plugin. As for the ping command, you have permissions for that.
![image](https://user-images.githubusercontent.com/100840109/187069315-9e28a249-79ec-46dd-ab6b-548a8023344b.png)

**Comment by Whizyyy** [comment]
Like @xpghard said you can use a plugin to do this, or purchase the Premium plan on https://shop.imanity.dev to customize the commands.
