### ISSUE TITLE
Adding PlayerOnGroundEvent

### ISSUE THREAD

**Issue by ProPractice** [Imanity-Software/ImanitySpigot3-git#58]
### Is your feature request related to a problem?

Some of my plugins on my server use this event. If not added to the spigot directly, an addon would be nice.

### Describe the solution you'd like.

If these patches could be implemented from SportPaper it would be nice:
https://github.com/Electroid/SportPaper/blob/master/patches/api/0007-Add-onGround-API.patch
https://github.com/Electroid/SportPaper/blob/master/patches/server/0016-Add-onGround-API.patch

### Describe alternatives you've considered.

I haven't tried any alternatives.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest ImanitySpigot3.

**Comment by Whizyyy** [comment]
Thanks for the feature request, added in 2021.11.1 LTS BUILD 3
