### ISSUE TITLE
Server wont start due to change in startup flags

### ISSUE THREAD

**Issue by dabou0** [Imanity-Software/ImanitySpigot3-git#59]
### Expected behavior

Server to start normally

### Observed/Actual behavior

Server will give an error and wont start
![image](https://user-images.githubusercontent.com/34607217/142088596-2cfd08ee-fe84-42a3-89ef-c32a9f55e552.png)

### Steps/models to reproduce

Starting the server will give the error
When added -Dfile.encoding=UTF-8 to startup flags

asked by kangarko 
https://github.com/kangarko/ChatControl-Red/issues/1467

### Plugin list

Im willing to give in private, but i think its not needed due to the type of this error.

### ImanitySpigot3 version

2021.10.1 BUILD 14

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

**Comment by LeeGodSRC** [comment]
Please try removing /imanity/rancha.yml and restart to let it generate the file

**Comment by dabou0** [comment]
it worked
