### ISSUE TITLE
User Client Crash

### ISSUE THREAD

**Issue by MrIBlob** [Imanity-Software/ImanitySpigot3-git#60]
### Stack trace

```
https://paste.imanity.dev/nojJy0d
```

### Plugin list

Plugins (16): Citizens (2.0.16-SNAPSHOT (build 1267)), FastAsyncWorldEdit (21.03.26-b67f782-1287-22.3.10), spark (1.5.2), WorldLoader (1.1), ProtocolLib (4.7.0), GodsEye (Build 49 HotFix-3), AntiCrash (3.1), WorldEdit (6.1.5;4651611), AntiTAB (1.0.1), HolographicDisplays (2.4.6), NetworkManager (2.9.9-SNAPSHOT), ProtocolSupport (4.22.1), WorldGuard (6.1 with custom flags plugin.), WGRegionEvents (1.1), TAB (2.9.2), WGCustomFlags (1.8.1-beta)

### Steps/models to reproduce (if known)

not known

### ImanitySpigot3 version

spigotJarVersion: 2021.11.1 LTS BUILD 2

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

**Comment by Whizyyy** [comment]
Please try the latest version: 2021.11.1 LTS BUILD 5, your issue is normally fixed
