### ISSUE TITLE
AsyncTabComplete

### ISSUE THREAD

**Issue by xpghard** [Imanity-Software/ImanitySpigot3-git#64]
### Expected behavior

AsyncTabCompleteEvent does not work properly.
I was expecting a full replenishment of the previously writed command.

### Observed/Actual behavior

I saw this
https://imgur.com/a/2VvUwRB

### Steps/models to reproduce

https://imgur.com/a/2VvUwRB

### Plugin list

1 Custom plugin CODE in java:

package pl.voidmc.core;

import org.bukkit.*;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.plugin.java.*;
import org.imanity.imanityspigot.event.AsyncTabCompleteEvent;

import java.util.Arrays;

public class CorePlugin
        extends JavaPlugin
        implements Listener {

    public static CorePlugin instance;

    @Override
    public void onEnable() {
        instance = this;

        getServer().getPluginManager().registerEvents(this, this);

    }

    @EventHandler
    public void onAutoComplete(AsyncTabCompleteEvent event){
        event.setCompletions(
                Arrays.asList(
                        "/mycommand",
                        "/bukkit"
                ));

    }

### ImanitySpigot3 version

2021.11.1 LTS BUILD 4

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

**Comment by Whizyyy** [comment]
Hello, to give some "flexibility" to this event we decided to no doing ourself the filtering of words. You have to do youself in the event when you want a word to be in the completion. If you have trouble doing this you can open a ticket on the discord server.
