### ISSUE TITLE
talibanPearl

### ISSUE THREAD

**Issue by xpghard** [Imanity-Software/ImanitySpigot3-git#65]
### Expected behavior

I think not teleport player on right click on stairs

### Observed/Actual behavior

https://imgur.com/a/7gRZC5t

### Steps/models to reproduce

https://imgur.com/a/7gRZC5t

### Plugin list

0 plugins
only config:

  talibanPearl:

    # Should taliban pearl be enabled?
    enabled: true

    # Allow slabs to execute Taliban Pearl behaviour
    slabCanThrough: true

    # Allow stairs to execute Taliban Pearl behaviour
    stairsCanThrough: true

    # Other Block types that are allowed to execute Taliban Pearl behaviour
    blockCanThrough:
    - ENCHANTMENT_TABLE
    - ENDER_PORTAL_FRAME

    # This is a value to determine is Player attempting to perform taliban pearl
    # The higher the value is, the more straight the pearl should be shoot
    horizontalMotionTaliban: 0.05

  # The AntiGlitch system for Ender Pearls
  # It will cache valid position every tick Ender Pearl move
  # And use the last cached valid position for teleportation.
  antiGlitch:

    # Should taliban pearl be enabled?
    enabled: true

    # Prevent Ender Pearl from Suffocating to blocks.
    antiSuffocation: true

    # If Pearl's current position is a part of prohibited pearl blocks
    # The position will not be determined as valid position.
    prohibitedPearlBlocks:
    - FENCE
    - FENCE_GATE

### ImanitySpigot3 version

2021.11.1 LTS BUILD 4

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

**Comment by Whizyyy** [comment]
Hello, please explain more the "Expected behavior" part

**Comment by xpghard** [comment]
I think enderpearl on right click on fance gate not teleport behind the wall lol.

**Comment by LeeGodSRC** [comment]
I'm confused about your report, First you messed up the report format which cause it harder to read in general
and you say ``I think not teleport player on right click on stairs``, and speak ``I think enderpearl on right click on fance gate not teleport behind the wall lol.`` to reply @Whizyyy 's question, and your title called "talibanPearl" which doesn't even have a proper title...
what exactly is the issue you are trying to report...
