### ISSUE TITLE
An option for snowball to go through fencegate

### ISSUE THREAD

**Issue by xpghard** [Imanity-Software/ImanitySpigot3-git#66]
### Is your feature request related to a problem?

I want if fancagate open snowball can go threw fancagete.

### Describe the solution you'd like.

I want if fancagate open snowball can go threw fancagete.
Now working like this https://imgur.com/a/RUFuWxq

### Describe alternatives you've considered.

...

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest ImanitySpigot3.

**Comment by LeeGodSRC** [comment]
Added in **2021.12.1 BUILD 2**
