### ISSUE TITLE
Unexpected double eat fix patch

### ISSUE THREAD

**Issue by iSilviu-debug** [Imanity-Software/ImanitySpigot3-git#67]
### Is your feature request related to a problem?

*I think this bug is still there*

Let's take an example of the golden apple.
Every time, in 1.8, I take an apple in my hand and click the right button and the Q button (button to drop) at the same time, I don't see the animation I'm eating, but after a few seconds it is eaten.

When we don't see the animation, we can run around eating any food.
Usually when you eat, the character slows down, but here's it seems to use a "Hacked Client with NoDelayFood".

### Describe the solution you'd like.

I did not see the package code, but you should cancel the food packet when it is no longer eaten. 
* Many servers have already fixed * 

### Describe alternatives you've considered.

*This is the procedure of how to prove this bug*

1) Join the game. 
2) Grab a quantity of golden apples to test this bug.
3) Get into survival and right click with the Q button at the same time.
4) Wait a few seconds, and if you've done it right, it should eat it.
5) If it doesn't work, try several times.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest ImanitySpigot3.

### Other

I hope I have described everything clearly. This bug is from spigot 1.8 which has been around for years now.
*Not an Imanity bug*

**Comment by Whizyyy** [comment]
Added in **2021.12.1 BUILD 2**
You can now toggle to true the option `eatAndDropFix` to fix this glitch
