### ISSUE TITLE
netty-incubator-transport-io_uring (IO_URING)

### ISSUE THREAD

**Issue by iSilviu-debug** [Imanity-Software/ImanitySpigot3-git#69]
### Is your feature request related to a problem?

I would like this netty addiction to be added as an experimental method.
This interface helps and reduces the bandwidth in use and the cpu which, for example, to servers that have many players is quite useful.

### Describe the solution you'd like.

Add this project. Maybe it can also be useful:
https://github.com/PaperMC/Velocity/tree/experiment/io_uring

### Describe alternatives you've considered.

-

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest ImanitySpigot3.

### Other

If you add this feature, it would be the best. I have a very high performance on my own proxy, both of cpu and connection.
🌵

**Comment by Xefreh** [comment]
Issue closed. Apparently won't be added.
