### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by FlopsFX** [Imanity-Software/ImanitySpigot3-git#71]
### Stack trace

```
paste your stack trace or a https://paste.imanity.dev/ link here!
```
06.12 20:27:06 [Server] INFO Enum protocol matched
06.12 20:27:11 [Server] ERROR *Man minecraft is a shitty game...*
06.12 20:27:11 [Server] ERROR The server has stopped responding!
06.12 20:27:11 [Server] ERROR Please report this to Imanity directly!
06.12 20:27:11 [Server] ERROR Report to here!: https://github.com/Imanity-Software/ImanitySpigot3-git
06.12 20:27:11 [Server] ERROR Be sure to include ALL relevant console errors and Minecraft crash reports
06.12 20:27:11 [Server] ERROR ImanitySpigot3 version: 2021.11.1 LTS BUILD 5
06.12 20:27:11 [Server] ERROR ------------------------------
06.12 20:27:11 [Server] ERROR Server thread dump (Look for plugins here before reporting to Imanity! >:(
06.12 20:27:11 [Server] ERROR ------------------------------
06.12 20:27:11 [Server] ERROR Current Thread: Server thread
06.12 20:27:11 [Server] ERROR PID: 20 | Suspended: false | Native: false | State: RUNNABLE
06.12 20:27:11 [Server] ERROR Stack:
06.12 20:27:11 [Server] ERROR net.minecraft.server.v1_8_R3.World.getCubes(SourceFile:1754)
06.12 20:27:11 [Server] ERROR net.minecraft.server.v1_8_R3.World.getCubes(SourceFile:1490)
06.12 20:27:11 [Server] ERROR net.minecraft.server.v1_8_R3.Entity.move(SourceFile:594)
06.12 20:27:11 [Server] ERROR net.minecraft.server.v1_8_R3.EntityLiving.g(SourceFile:1512)
06.12 20:27:11 [Server] ERROR net.minecraft.server.v1_8_R3.EntityHuman.g(SourceFile:1470)
06.12 20:27:11 [Server] ERROR net.minecraft.server.v1_8_R3.EntityLiving.m(SourceFile:1762)
06.12 20:27:11 [Server] ERROR net.minecraft.server.v1_8_R3.EntityHuman.m(SourceFile:483)
06.12 20:27:11 [Server] ERROR net.minecraft.server.v1_8_R3.EntityLiving.t_(SourceFile:1602)
06.12 20:27:12 [Server] ERROR net.minecraft.server.v1_8_R3.EntityHuman.t_(SourceFile:262)
06.12 20:27:12 [Server] ERROR net.minecraft.server.v1_8_R3.EntityPlayer.l(SourceFile:393)
06.12 20:27:12 [Server] ERROR net.minecraft.server.v1_8_R3.PlayerConnection.a(SourceFile:515)
06.12 20:27:12 [Server] ERROR net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:31)
06.12 20:27:12 [Server] ERROR net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:96)
06.12 20:27:12 [Server] ERROR net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:21)
06.12 20:27:12 [Server] ERROR java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
06.12 20:27:12 [Server] ERROR java.util.concurrent.FutureTask.run(FutureTask.java:266)
06.12 20:27:12 [Server] ERROR net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:18)
06.12 20:27:12 [Server] ERROR net.minecraft.server.v1_8_R3.MinecraftServer.B(SourceFile:938)
06.12 20:27:12 [Server] ERROR net.minecraft.server.v1_8_R3.DedicatedServer.B(SourceFile:502)
06.12 20:27:12 [Server] ERROR net.minecraft.server.v1_8_R3.MinecraftServer.A(SourceFile:868)
06.12 20:27:12 [Server] ERROR net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:769)
06.12 20:27:12 [Server] ERROR java.lang.Thread.run(Thread.java:748)
06.12 20:27:12 [Server] ERROR ------------------------------
06.12 20:27:12 [Server] ERROR Entire Thread Dump:

### Plugin list

![image](https://user-images.githubusercontent.com/90907326/144909959-9a717527-e5e9-4545-b28f-a785effbffa0.png)

### Steps/models to reproduce (if known)

I dont know...

### ImanitySpigot3 version

2021.11.1 LTS BUILD 5

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

### Other

It just happens randomly , people can still type in chat but everything is frozen.

**Comment by FlopsFX** [comment]
could someone help lol

**Comment by LeeGodSRC** [comment]
Hello, can you show us your `/imanity/config.yml` please?

**Comment by FlopsFX** [comment]
here https://www.mediafire.com/file/iulilf419yfk0lx/config.yml/file

**Comment by LeeGodSRC** [comment]
It seems like a crasher to me but due to lack of information we cannot take any actions yet

**Comment by Whizyyy** [comment]
No update since a long time, issue considered as fixed.
