### ISSUE TITLE
NMS World.addEntity(EntityTNTPrimed) make the tnt disappears if called multiple time (TNT Merger)

### ISSUE THREAD

**Issue by NivixX** [Imanity-Software/ImanitySpigot3-git#73]
### Expected behavior

Sample code (basically I'm calling World.addEntity 10 times), feel free to test by yourself :

    @EventHandler
    public void test(PlayerInteractEvent e) {
        if(e.getAction() == Action.LEFT_CLICK_AIR) {
            for(int i=0; i<10; i++) {
                Location loc = e.getPlayer().getLocation();
                CraftWorld world = (CraftWorld) loc.getWorld();
                EntityTNTPrimed entityTNTPrimed = new EntityTNTPrimed(loc, world.getHandle(), loc.getX(), loc.getY(), loc.getZ(), null);
                Entity tnt = ((CraftWorld) loc.getWorld()).addEntity(entityTNTPrimed, CreatureSpawnEvent.SpawnReason.NATURAL);
            }
        }
    }
    
    
  It's supposed to spawn 10 tnt

### Observed/Actual behavior

For some reason, all my tnt disappears after like 1 tick. Note that I don't have the issue if I only do it once instead of 10 times.
I don't have the issue in ISpigot2 or a regular paper

If I'm using "World.spawn(Location var1, Class<T> var2)" I don't have the issue but I really need to use the addEntity method

### Steps/models to reproduce

copy paste my sample code and test it

### Plugin list

above

### ImanitySpigot3 version

2021.11.1 LTS BUILD 6

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

**Comment by LeeGodSRC** [comment]
Hey, I think it's because of our TNT merger system, if two TNT are having similar position, velocity, and tick time, then it will be merged and added up to the "power" value where it will increase explode damage.

You can try to make the velocity between each tnt different it shouldn't be merged

**Comment by NivixX** [comment]
Hello, thank you for your response.

Oh that's indeed a nice feature, I'm not sure why it doesn't happens with the "World.spawn()" though. I think these kind of optimisations should be configurable because as I'm running a faction server, it may be incompatible with a lot of base raid system using tnt (and most of these plugin use tnt count explosion instead of power).
In my case, I've made a catapult that can throw multiple tnt in a precise direction for long distances so editing velocity will break the feature.

**Comment by Whizyyy** [comment]
Added in **2021.12.1 BUILD 2**
You can now customize in the configuration how the optimizations about TNT works and toggle them. So you can disable the TNT Merger to solve your issue.
