### ISSUE TITLE
Change limit characters on message

### ISSUE THREAD

**Issue by XBeTeRR** [Imanity-Software/ImanitySpigot3-git#74]
### Is your feature request related to a problem?

Probably imanity spigot blocks sending messages and commands over 100 characters 

### Describe the solution you'd like.

Adding to the configuration the change of the limit of the sent message length (100 to 256 characters) because our client has an increased lock to 256 and added colors in HEX which means that we cannot use them too much with a limit of 100 .

### Describe alternatives you've considered.

Adding to config the possibility of increasing the number of characters.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest ImanitySpigot3.

### Other

![photo](https://user-images.githubusercontent.com/89166198/146651584-41df09e2-6437-47c1-9ca3-b7fd59db04d2.png)

**Comment by LeeGodSRC** [comment]
Added in **2021.12.1 BUILD 2**
