### ISSUE TITLE
spam tab complete disconnect player and unable to rejoin

### ISSUE THREAD

**Issue by XBeTeRR** [Imanity-Software/ImanitySpigot3-git#75]
### Expected behavior

The player after using TAB and throwing out for disconnect.spam stays on the server and can only be removed by restarting the server

### Observed/Actual behavior

Only when using Async TabCompleteEvent the player remains non-removable from the server

### Steps/models to reproduce

https://user-images.githubusercontent.com/89166198/146653381-50b7e5a4-90cb-4fbb-886e-cee3c8da1721.mp4

### Plugin list

VoidGen (2.0), ProtocolLib (4.7.0), My plugins

### ImanitySpigot3 version

spigotJarVersion: 2021.12.1 BUILD 1

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

**Comment by Whizyyy** [comment]
Hey, can you please provide more informations? How are you using the AsyncTabCompleteEvent?

**Comment by XBeTeRR** [comment]
Przy AsyncTabCompleteEvent używam e.setCancelled(true);  i trzymam przycisk TAB. Po 5 sekundach zostaje wyrzucony za disconnect.spam. Po wyrzuceniu gracz i tak zostaje na serwerze. Nie można go w żaden sposób usunąć z serwera. Tylko restart serwera

**Comment by XBeTeRR** [comment]
With AsyncTabCompleteEvent I am using e.setCancelled (true); and I hold the TAB button. After 5 seconds it gets thrown for disconnect.spam. After being thrown, the player stays on the server anyway. It cannot be removed from the server in any way. Server restart only

**Comment by XBeTeRR** [comment]
still error occurs (2021.12.1 BUILD 2)
