### ISSUE TITLE
Fishing Rods Launch hook is not as fast as iSpigot2, and there is a delay.

### ISSUE THREAD

**Issue by LeSGYT** [Imanity-Software/ImanitySpigot3-git#76]
### Expected behavior

to see faster rods, (in launch not after launch "since I can change this using knockback behavior")

### Observed/Actual behavior

I see slow & very delayed rods compared to iSpigot2, or other optimized spigots.

### Steps/models to reproduce

I will send the videos in private.

### Plugin list

I will send plugins in private

### ImanitySpigot3 version

ImanitySpigot3 at all versions.

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

### Other

this is not about after the rod is launched, it's about the launching itself being delayed, or slow & sometimes will double hook.

**Comment by LeeGodSRC** [comment]
We will count it as a feature request rather than bug, the "delay" is caused due to how minecraft server stacks up all incoming packets and process together at once on beginning of the tick, which can delayed up to 50ms at maximum. we will be adding a feature that improves this case in next update.
