### ISSUE TITLE
Update ChatColor.class

### ISSUE THREAD

**Issue by XBeTeRR** [Imanity-Software/ImanitySpigot3-git#77]
### Is your feature request related to a problem?

No possibility of using colors in HEX by our client by the ChatColor class. 

### Describe the solution you'd like.

Added to the configuration of using HEX colors by ChatColor.of() class because our client has added HEX colors and other clients can add it (lunar client, badlion).

### Describe alternatives you've considered.

https://github.com/SpigotMC/BungeeCord/blob/master/chat/src/main/java/net/md_5/bungee/api/ChatColor.java
ChatColor.of();

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest ImanitySpigot3.

**Comment by Whizyyy** [comment]
After taking your suggestion into consideration, we decided not to add this to ImanitySpigot3. If you have your own client you can most likely add this kind of thing yourself via a plugin. Thanks for the suggestion.
