### ISSUE TITLE
enderpearls don't work as they should 

### ISSUE THREAD

**Issue by itzslashmc** [Imanity-Software/ImanitySpigot3-git#79]
### Expected behavior

Should always teleport because many of my users complain that they do not work as they should and the second bug looks like pearl inside but covers it outside 

### Observed/Actual behavior

Here is a demonstration of the two errors that I have encountered and the configuration that I am currently using: https://www.youtube.com/watch?v=vqBBxTydjzs

### Steps/models to reproduce

Video: https://www.youtube.com/watch?v=vqBBxTydjzs
Schematic: https://www.mediafire.com/file/nptkx8dfqurkvzf/imanity-bug.schematic/file

### Plugin list

https://gyazo.com/682fbc56f847767fe38405b9d86a3d36

### ImanitySpigot3 version

spigotJarVersion: 2021.11.1 LTS BUILD 6

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

**Comment by Whizyyy** [comment]
Hello, please test with the option `enderPearl.talibanPearl.enabled = true`

**Comment by itzslashmc** [comment]
> Hello, please test with the option `enderPearl.talibanPearl.enabled = true`

the bug keeps happening
https://www.youtube.com/watch?v=ERDFe_SQssQ

**Comment by Whizyyy** [comment]
You are placed very close to the stairs, so the enderpearl reaches you and the player is not teleported with you. It's not really a bug but that's how it's supposed to work. However, we may consider an option to fix this in the pearl system. Please make a feature request about it, thanks!

**Comment by itzslashmc** [comment]
> You are placed very close to the stairs, so the enderpearl reaches you and the player is not teleported with you. It's not really a bug but that's how it's supposed to work. However, we may consider an option to fix this in the pearl system. Please make a feature request about it, thanks!

Can't you create something to teleport you even if you can bug ur self?
