### ISSUE TITLE
Player kick

### ISSUE THREAD

**Issue by XBeTeRR** [Imanity-Software/ImanitySpigot3-git#80]
### Expected behavior

Everything is shown in the picture 

### Observed/Actual behavior

Everything is shown in the picture 

### Steps/models to reproduce

Everything is shown in the picture
![Bez tytułu](https://user-images.githubusercontent.com/89166198/147419194-d4b2af8e-3faf-4d9b-8323-24d531d0c8f9.png)
 

### Plugin list

VoidGen (2.0), ProtocolLib (4.7.0), My plugins

### ImanitySpigot3 version

spigotJarVersion: 2021.12.1 BUILD 2

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

**Comment by LeeGodSRC** [comment]
I couldn't understand what you saying, can you please explain more?

**Comment by Whizyyy** [comment]
The outcome did not respect the format requested and there has been no response for 15 days. Considered as fixed.
