### ISSUE TITLE
Improvement for arrows knockback

### ISSUE THREAD

**Issue by itzslashmc** [Imanity-Software/ImanitySpigot3-git#82]
### Is your feature request related to a problem?

Yes, the punch system should be changed as I feel that punching in imanity is much more unstable, not all arrows push you the same and there are even times that it pushes little, (it's nothing about the configuration). Currently we use a plugin to make the arrow push me straight as in imanity it pushes me like in vanilla spigot. On servers such as InvadedLands or Ecuacraft it is much easier to punch each other because of their punch system.

### Describe the solution you'd like.

Just explain above how it should be and now I will put some examples comparing imanity with other spigots:
Custom paper spigot vs imanity https://www.youtube.com/watch?v=Bpr0D-miaLY
you can see that the thrust of the arrow is more constant on the custom paper spigot
I wouldn't know how to explain it to you so that you can understand it basically improve the thrust of the arrow.
Other example how I should push the arrow: https://youtu.be/tSf0rtHqgDs?t=418

### Describe alternatives you've considered.

That hitting yourself with an arrow pushes you straight because having to add a plugin can affect with KnockBack.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest ImanitySpigot3.

### Other

<3

**Comment by LeeGodSRC** [comment]
Hello, since **2022.3.1 BUILD 2** an option called `arrowTrajectoryRandomness` has been added to imanity world config, can you try setting it to 0 and try to do self punch again and see if it improves?

**Comment by Whizyyy** [comment]
An option has been added to complete the feature request and no reply since. Considered as done
