### ISSUE TITLE
PlayerPortalEvent

### ISSUE THREAD

**Issue by LeSGYT** [Imanity-Software/ImanitySpigot3-git#83]
### Expected behavior

when a player jumps into a portal (or stays there) PlayerPortalEvent should be called

### Observed/Actual behavior

I have a game called TheBridge that has a portal inside it, whenever a player jump into this portal the plugin will make the player win, it works for the first time but the second time a player jumps in this portal PlayerPortalEvent is not called even though on regular spigot it is

### Steps/models to reproduce

Jump in the portal or stay in it, multiple times.

### Plugin list

I will send this in DM's for LeeGod

### ImanitySpigot3 version

2021.12.1 BUILD 2

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

### Other

I have tried the same game with regular spigot/taco 1.8.8 and it didn't happen, It only happened on ImanitySpigot

**Comment by Sushirod** [comment]
Hi Im having the same issue !! Please could you fix it 🗡️
