### ISSUE TITLE
Event not working with items

### ISSUE THREAD

**Issue by xpghard** [Imanity-Software/ImanitySpigot3-git#84]
### Expected behavior

I want to event catch this...

### Observed/Actual behavior

When i drop item to void event death not printing is item dead...

### Steps/models to reproduce

.

### Plugin list

0 plugins

### ImanitySpigot3 version

2021.12.1 BUILD 2

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

**Comment by Whizyyy** [comment]
Hello, after testing on our side it print well the item as dead. Can you show us how you check if the item is dead or not? Please send us the more information as possible

**Comment by xpghard** [comment]
I use EntityDamageEvent ItemDespawnEvent events
   @EventHandler
    public void onEntityDamageEvent(EntityDamageEvent event){
        System.out.println("EntityDamageEvent");
    }

    @EventHandler
    public void onItemDespawnEvent(ItemDespawnEvent event){
        System.out.println("ItemDespawnEvent");
    }

**Comment by xpghard** [comment]
> Hello, after testing on our side it print well the item as dead. Can you show us how you check if the item is dead or not? Please send us the more information as possible

can you send how to do that?
