### ISSUE TITLE
Built-in Fix for “disconnect.spam”

### ISSUE THREAD

**Issue by nicholasveronico** [Imanity-Software/ImanitySpigot3-git#87]
### Is your feature request related to a problem?

A common issue with bukkit is the kicking that occurs when commands are executed too frequently. The player gets kicked for “disconnect.spam”.

### Describe the solution you'd like.

Block any kick if the reason contains “disconnect.spam”, “disconnect spam”, or “ Kicked for spamming”.

### Describe alternatives you've considered.

Alternatively, there is a plugin called AntiDisconnectSpam (https://www.spigotmc.org/resources/antidisconnectspam-remove-disable-fix-and-change-disconnect-spam.33344/). However, it would be nice to have this in iSpigot.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest ImanitySpigot3.

**Comment by LeeGodSRC** [comment]
It is necessary to prevent any kind of spamming so we are unsure if we should remove it

**Comment by nicholasveronico** [comment]
> It is necessary to prevent any kind of spamming so we are unsure if we should remove it

Is it possible to have it as a toggle in the config, similar to the eat animation fix?

**Comment by Whizyyy** [comment]
We decided to not add this as an option since we consider it as not useful and dangerous. Please consider another solution and we advise you to not remove this through a plugin without knowing the possible bad effects.
