### ISSUE TITLE
PacketSend

### ISSUE THREAD

**Issue by xpghard** [Imanity-Software/ImanitySpigot3-git#90]
### Is your feature request related to a problem?

Because protocallib have a lot of bugs when reload etc. 

### Describe the solution you'd like.

Since there is an option to capture packets, it could also have been an option to send packets. Like in protocallib

### Describe alternatives you've considered.

.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest ImanitySpigot3.

**Comment by LeeGodSRC** [comment]
Hey, currently ImanitySpigot has PacketHandler that does similar job to capture packets which you can find docs here: https://docs.imanity.dev/books/imanityspigot-3/page/handlers
