### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Betterovsky** [Imanity-Software/ImanitySpigot3-git#91]
### Stack trace

Crash: https://paste.imanity.dev/YEB7LZv

### Plugin list

https://paste.imanity.dev/YEB7LZv

### ImanitySpigot3 version

2022.01.1 BUILD 2

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

### Other

The bug was in iSpigot 2.0 but it did not crash. Please help as the server is shutting down

**Comment by XBeTeRR** [comment]
https://github.com/PaperMC/Paper/issues/30

**Comment by Xayanix** [comment]
```
/*
    created by: Xayanix at 2022-02-17 20:54
*/
public class PacketPlayInWindowClickListener extends PacketAdapter {

    public PacketPlayInWindowClickListener() {
        super(Main.getInstance(), ListenerPriority.MONITOR, PacketType.Play.Client.WINDOW_CLICK);
        ProtocolLibrary.getProtocolManager().addPacketListener(this);
    }

    @Override
    public void onPacketReceiving(PacketEvent event) {
        Player player = event.getPlayer();
        int slot = event.getPacket().getIntegers().readSafely(1);

        if (slot >= player.getOpenInventory().countSlots()) {
            event.setReadOnly(false);
            event.setCancelled(true);
        }

    }
}
```
Should fix it.

**Comment by XBeTeRR** [comment]
@Xayanix It doesn't fix it, the error is still a crash 

```
[13:00:12] [INFO]: [BUKKIT] 54 - 1
[13:00:12] [INFO]: [BUKKIT] 90 - 2
[13:00:12] [INFO]: [BUKKIT] 49 - 3
[13:00:12] [ERROR]: Encountered an unexpected exception
java.lang.IndexOutOfBoundsException: Index: 49, Size: 45
	at java.util.ArrayList.rangeCheck(ArrayList.java:659) ~[?:1.8.0_322]
	at java.util.ArrayList.get(ArrayList.java:435) ~[?:1.8.0_322]
	at net.minecraft.server.v1_8_R3.Container.getSlot(SourceFile:118) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(SourceFile:1902) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:27) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:18) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils.lambda$ensureMainThread$0(SourceFile:105) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils.awaitTasks(SourceFile:70) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:745) ~[spigot.jar:git-iSpigot-PaperEdition]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_322]
```

```
        APIMain.getProtocolManager().addPacketListener(new PacketAdapter(APIMain.getPlugin(), ListenerPriority.MONITOR, PacketType.Play.Client.WINDOW_CLICK) {
            @Override
            public void onPacketReceiving(PacketEvent event) {
                Player player = event.getPlayer();
                Logger.log("      ");
                Logger.log(player.getOpenInventory().getTopInventory().getSize() + " - 1");
                Logger.log(player.getOpenInventory().countSlots() + " - 2");
                Logger.log(event.getPacket().getIntegers().readSafely(1) + " - 3");
            }
        });
```

**Comment by XBeTeRR** [comment]
crash:
```
p.closeInventory();
```

fix crash:
```
Bukkit.getScheduler().runTaskLater(APIMain.getPlugin(), () -> p.closeInventory(), 1L);
```

**Comment by Xayanix** [comment]
> @Xayanix It doesn't fix it, the error is still a crash
> 
> ```
> [13:00:12] [INFO]: [BUKKIT] 54 - 1
> [13:00:12] [INFO]: [BUKKIT] 90 - 2
> [13:00:12] [INFO]: [BUKKIT] 49 - 3
> [13:00:12] [INFO]: [BUKKIT] [1, 49, 1, 0] - 4
> [13:00:12] [ERROR]: Encountered an unexpected exception
> java.lang.IndexOutOfBoundsException: Index: 49, Size: 45
> 	at java.util.ArrayList.rangeCheck(ArrayList.java:659) ~[?:1.8.0_322]
> 	at java.util.ArrayList.get(ArrayList.java:435) ~[?:1.8.0_322]
> 	at net.minecraft.server.v1_8_R3.Container.getSlot(SourceFile:118) ~[spigot.jar:git-iSpigot-PaperEdition]
> 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(SourceFile:1902) ~[spigot.jar:git-iSpigot-PaperEdition]
> 	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:27) ~[spigot.jar:git-iSpigot-PaperEdition]
> 	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:18) ~[spigot.jar:git-iSpigot-PaperEdition]
> 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils.lambda$ensureMainThread$0(SourceFile:105) ~[spigot.jar:git-iSpigot-PaperEdition]
> 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils.awaitTasks(SourceFile:70) ~[spigot.jar:git-iSpigot-PaperEdition]
> 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:745) ~[spigot.jar:git-iSpigot-PaperEdition]
> 	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_322]
> [13:00:12] [ERROR]: This crash report has been saved to: /home/sezon/lobby-1/./crash-reports/crash-2022-02-18_13.00.12-server.txt
> [13:00:12] [INFO]: Stopping server
> [13:00:12] [INFO]: lobby - Scheduler shutdown completed.
> ```
> 
> ```
>         APIMain.getProtocolManager().addPacketListener(new PacketAdapter(APIMain.getPlugin(), ListenerPriority.MONITOR, PacketType.Play.Client.WINDOW_CLICK) {
>             @Override
>             public void onPacketReceiving(PacketEvent event) {
>                 Player player = event.getPlayer();
>                 Logger.log("      ");
>                 Logger.log(player.getOpenInventory().getTopInventory().getSize() + " - 1");
>                 Logger.log(player.getOpenInventory().countSlots() + " - 2");
>                 Logger.log(event.getPacket().getIntegers().readSafely(1) + " - 3");
>                 Logger.log(event.getPacket().getIntegers().getValues() + " - 4");
>             }
>         });
> ```

I tested my solution thoroughly and it works fine in my case. What you sent does not solve the problem, because player can send the malicious packet using the hacked client.

**Comment by Betterovsky** [comment]
@LeeGodSRC @Whizyyy

**Comment by Whizyyy** [comment]
Issue fixed in latest updates
