### ISSUE TITLE
Arrow and projectile randomization 

### ISSUE THREAD

**Issue by Boryte** [Imanity-Software/ImanitySpigot3-git#92]
### Is your feature request related to a problem?

No. 

### Describe the solution you'd like.

Add an option in the config to make projectiles and arrow go in the same path. This was already a feature in 1.7 but randomization got added in 1.8.
It makes long distance shots and rodding luck based. If projectiles all had same linear path without randomization it'd be more skill based. 

### Describe alternatives you've considered.

Only alternative is Old Combat Mechanics but that plugin is only available for 1.9+

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest ImanitySpigot3.

**Comment by LeeGodSRC** [comment]
An option called `arrowTrajectoryRandomness` has been added to imanity world config in **2022.3.1 BUILD 2**
