### ISSUE TITLE
Durability update crashes the server when the target player is in different inventory

### ISSUE THREAD

**Issue by CoOwner** [Imanity-Software/ImanitySpigot3-git#93]
### Expected behavior

Once player is hit while GUI is opened, player takes damage and server should keep running.

### Observed/Actual behavior

If player is hit with **ARMOR** while a GUI is opened (can be virtual, can be chest GUI), server breaks.

### Steps/models to reproduce

Go to imanity config.yml, go to `durabilityMultiplier:` change the value **lower** than 1.0, startup the server, get armor on yourself (from helmet to boots), open a chest, get a second player to hit you and boom, server crashes. 

### Plugin list

> pl
[19:44:48 INFO]: Plugins (18): CoreProtect (2.10.0), Citizens (2.0.24-SNAPSHOT (build 1605)), FastAsyncWorldEdit (18.05.02-89bd2c0-1105-19.7.10), VoidWorld (1.0), SpigotGuard (6.4.2 BULLET-PROOF), spark (1.5.2), CommandNPC (1.9.1), CraftingStore (2.8.0), Pivot (${git.commit.id.abbrev}), ProtocolSupport (4.23.dev), ProtocolLib (4.4.0), BunniLibrary (d9e03d3), Spartan (575ab73), WorldEdit (6.1.5;4651611), Friends-Spigot (f66dde6), KarhuLoader (1.0), SoupPvP (${git.commit.id.abbrev}-${git.branch}), Modcore (1.0-SNAPSHOT)

### ImanitySpigot3 version

spigotJarVersion: 2022.01.1 BUILD 2

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

### Other

![image](https://user-images.githubusercontent.com/43219441/155017748-cd27af16-d710-4fc4-a54c-47f17ad4e33c.png)

Above is more information if needed. 

I HAVE tried PlayerItemDamageEvent in the code and still happens while the value is at 1.0 in the config.

**Comment by LeeGodSRC** [comment]
Can you show the log error please?

**Comment by CoOwner** [comment]
https://paste.gg/p/anonymous/ef7fae19bc7c46fb831106835e10a84a, https://paste.gg/p/anonymous/8b17b27b19fc4238ad921b4813191dab

**Comment by CoOwner** [comment]
it doesn't crash anymore, but the armor gets placed in the chest GUI. https://gyazo.com/4ff7afa6357ce1b180c65bd6d08ffd6e
The items doesnt actually stay in there, it seems like its some sort of visual bug, but here another gif.
https://gyazo.com/fd0dcf9edc93777bc4df37eba42504a6
Same steps to reproduce, but instead of the server crashing, this now happens.

**Comment by LeeGodSRC** [comment]
Fixed in **2022.3.1 BUILD 1**
