### ISSUE TITLE
Hologram names doing weird things when playing on ver 1.7.10 

### ISSUE THREAD

**Issue by Redwolf223** [Imanity-Software/ImanitySpigot3-git#95]
### Expected behavior

For the holograms to work properly.

### Observed/Actual behavior

Holograms disappearing / duplicating.

![image](https://user-images.githubusercontent.com/58572866/156386425-3c5f5ac7-b230-42fd-8a14-d48cad9b96bd.png)

https://gyazo.com/c637941565b19b8d371fb86dab8d98a1

### Steps/models to reproduce

Use TAB v3.0.2 and ViaVersion playing in 1.7.10 and shifting.

### Plugin list

Testing with:

ViaVersion, ViaRewind, TAB, CMI, LPX, LeaderHeads, ProtocolLib, Multiverse Core, TAB, CMI, 

### ImanitySpigot3 version

2022.01.1 BUILD 3

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

**Comment by LeeGodSRC** [comment]
After some testing, we wasn't able to reproduce the same issue with ViaVersion (4.2.1), ViaRewind (2.0.2), TAB (3.0.2)
We might need your entire setup to verify, were you able to send the setup here? or privately.

**Comment by Redwolf223** [comment]
Hello, we re-tried only with the plugins you listed and the same version.

https://gyazo.com/54c7b0345ed61938b126462984f33a55 , this was the result.

Before giving you my setup, i would like to ask you if you were testing with 1.7.10. Thank you.

**Comment by Redwolf223** [comment]
Fixed it by resetting the TAB folder completely. Sorry for making you lose time.
