### ISSUE TITLE
Strikepractice bots

### ISSUE THREAD

**Issue by ItzNg** [Imanity-Software/ImanitySpigot3-git#97]
### Expected behavior

Strikepractice bot seems to have a weird issue where every 5-10 hits or so, it will cancel the kb but not hit, making the bots fell off and unnatural. 

### Observed/Actual behavior

This only happens with citizens' pathfinder.

### Steps/models to reproduce

Run strike and citizens' pathfinder use-new.path: true

### Plugin list

![5qaq6fdOj](https://user-images.githubusercontent.com/64746743/157543971-dc789141-172b-4218-9f46-4afe7e055a76.png)

### ImanitySpigot3 version

2022.01.1 BUILD 3

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

**Comment by Whizyyy** [comment]
If this is an issue from Citizens Pathfinder, then please report this to the developer of this plugin.
