### ISSUE TITLE
Crash upon generating map

### ISSUE THREAD

**Issue by EBPPO** [Imanity-Software/ImanitySpigot3-git#98]
### Stack trace

Crash: https://paste.imanity.dev/zzKIwUe

### Plugin list

WorldBorder, custom UHC Plugin that depends on it.

### ImanitySpigot3 version

2021.11.1 LTS BUILD 6

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

**Comment by LeeGodSRC** [comment]
The paste link seems to be expired, can you send one again?

**Comment by Whizyyy** [comment]
Closed due to inactivity, probably fixed since.
